import type { Metadata } from 'next';
import Link from 'next/link';
import Navbar from '@/components/Navbar';
import BackButton from '@/components/BackButton';
import SiteFooter from '@/components/SiteFooter';

/**
 * Documentation page for the public static JSON API generated by
 * scripts/generate-api-json.js. The API is purely static (just .json files
 * in public/api/v1/) so this page is also a server component with no client
 * dependencies — keeps the bundle minimal.
 */

export const metadata: Metadata = {
  title: 'Public LLM Compatibility API — localllm-advisor',
  description:
    'Free, static, CORS-friendly JSON API for local LLM hardware compatibility. ' +
    'Per-GPU recommendations, per-model compatibility tables, tier list — all CDN-served.',
  alternates: { canonical: '/api' },
  openGraph: {
    title: 'Public LLM Compatibility API',
    description:
      'Free, static JSON API for local LLM hardware compatibility. CDN-served, CORS-friendly.',
    images: [{ url: '/og/og-home.svg', width: 1200, height: 630 }],
  },
};

const BASE = 'https://localllm-advisor.com/api/v1';

const ENDPOINTS: { path: string; method: string; desc: string; example?: string }[] = [
  {
    path: `${BASE}/index.json`,
    method: 'GET',
    desc: 'Top-level registry — version, generated_at, list of every endpoint with descriptions.',
  },
  {
    path: `${BASE}/models.json`,
    method: 'GET',
    desc: 'Lightweight directory of every model in the dataset (id, slug, family, params, benchmarks).',
  },
  {
    path: `${BASE}/gpus.json`,
    method: 'GET',
    desc: 'Lightweight directory of every GPU we have specs for (vram, bandwidth, vendor, tdp, price).',
  },
  {
    path: `${BASE}/tier-list.json`,
    method: 'GET',
    desc: 'Curated tier list (S/A/B/C/D) of canonical models grouped by VRAM ceiling. Same data the /tier-list page renders.',
  },
  {
    path: `${BASE}/gpu/{slug}.json`,
    method: 'GET',
    desc: 'Per-GPU summary: top recommendations across every use case.',
    example: `${BASE}/gpu/nvidia-rtx-4090.json`,
  },
  {
    path: `${BASE}/gpu/{slug}/{useCase}.json`,
    method: 'GET',
    desc: 'Per-(GPU, use case) ranked recommendations. Use cases: chat, coding, reasoning, creative.',
    example: `${BASE}/gpu/nvidia-rtx-4090/coding.json`,
  },
  {
    path: `${BASE}/model/{slug}.json`,
    method: 'GET',
    desc: 'Per-model: full quantization table + which popular GPUs can run it (with tps estimates).',
    example: `${BASE}/model/qwen-3-32b-dense.json`,
  },
];

const SAMPLE_GPU_RESPONSE = `{
  "schema": "localllm.advisor.gpu_recommendations@1.0.0",
  "generated_at": "2026-04-25T12:00:00.000Z",
  "gpu": {
    "slug": "nvidia-rtx-4090",
    "name": "NVIDIA RTX 4090",
    "vendor": "nvidia",
    "vram_mb": 24576,
    "bandwidth_gbps": 1008,
    "tdp_watts": 450,
    "price_usd": 1999
  },
  "use_case": "coding",
  "benchmark_channels": ["bigcodebench","humaneval","math","ifeval"],
  "count": 25,
  "recommendations": [
    {
      "id": "qwen3-coder-30b-a3b",
      "slug": "qwen3-coder-30b-a3b",
      "name": "Qwen3-Coder 30B A3B",
      "family": "qwen",
      "params_b": 30,
      "architecture": "moe",
      "quality_score": 70,
      "quant": "Q4_K_M",
      "bpw": 4.83,
      "vram_mb": 19200,
      "vram_pct": 78.1,
      "estimated_tps": 52
    }
    // ...
  ]
}`;

const PYTHON_EXAMPLE = `import requests

# Get the top coding models for an RTX 4090
r = requests.get("${BASE}/gpu/nvidia-rtx-4090/coding.json")
data = r.json()

print(f"Top 5 coding models on the {data['gpu']['name']}:")
for m in data["recommendations"][:5]:
    print(f"  {m['name']:30s} {m['quant']:8s} ~{m['estimated_tps']} tok/s")
`;

const JS_EXAMPLE = `const res = await fetch(
  "${BASE}/gpu/nvidia-rtx-4090/coding.json"
);
const data = await res.json();

for (const m of data.recommendations.slice(0, 5)) {
  console.log(\`\${m.name}  \${m.quant}  ~\${m.estimated_tps} tok/s\`);
}`;

const CURL_EXAMPLE = `# Top coding models for an RTX 4090
curl -s ${BASE}/gpu/nvidia-rtx-4090/coding.json | jq '.recommendations[:5]'

# Which GPUs can run Qwen 3 32B?
curl -s ${BASE}/model/qwen-3-32b-dense.json | jq '.runnable_on[:5]'`;

export default function ApiDocsPage() {
  return (
    <div className="min-h-screen flex flex-col">
      <Navbar />
      <BackButton />
      <main className="flex-1 mx-auto max-w-4xl px-4 py-10 w-full">
        <header className="mb-10">
          <h1 className="text-4xl md:text-5xl font-extrabold">
            Public <span className="text-emerald-500">JSON API</span>
          </h1>
          <p className="mt-3 text-lg text-gray-500 max-w-2xl">
            Free, static, CORS-friendly JSON for everything localllm-advisor
            knows about: GPU compatibility, ranked recommendations per use case,
            per-model VRAM tables, the tier list. CDN-served, no auth, no rate
            limits, no scraping.
          </p>
          <div className="mt-4 flex flex-wrap gap-2 text-xs">
            <span className="px-2 py-1 rounded-full bg-emerald-500/15 text-emerald-500 border border-emerald-500/40">
              Static / CDN-cached
            </span>
            <span className="px-2 py-1 rounded-full bg-emerald-500/15 text-emerald-500 border border-emerald-500/40">
              CORS: *
            </span>
            <span className="px-2 py-1 rounded-full bg-emerald-500/15 text-emerald-500 border border-emerald-500/40">
              CC BY 4.0
            </span>
            <span className="px-2 py-1 rounded-full bg-gray-500/15 text-gray-500 border border-gray-500/40">
              Schema v1.0.0
            </span>
          </div>
        </header>

        <section className="mb-10">
          <h2 className="text-2xl font-bold mb-3">Quick start</h2>
          <p className="text-gray-500 mb-4">
            Every endpoint is a plain JSON file under{' '}
            <code className="px-1.5 py-0.5 rounded bg-gray-200 dark:bg-gray-800 font-mono text-sm">
              {BASE}
            </code>
            . Hit it from any HTTP client — browser, fetch, requests, curl, even
            an LLM tool-call.
          </p>

          <h3 className="text-sm font-semibold mt-6 mb-2 text-gray-500 uppercase tracking-wide">curl</h3>
          <pre className="rounded-lg bg-gray-900 text-emerald-300 text-xs p-4 overflow-x-auto"><code>{CURL_EXAMPLE}</code></pre>

          <h3 className="text-sm font-semibold mt-6 mb-2 text-gray-500 uppercase tracking-wide">JavaScript / TypeScript</h3>
          <pre className="rounded-lg bg-gray-900 text-emerald-300 text-xs p-4 overflow-x-auto"><code>{JS_EXAMPLE}</code></pre>

          <h3 className="text-sm font-semibold mt-6 mb-2 text-gray-500 uppercase tracking-wide">Python</h3>
          <pre className="rounded-lg bg-gray-900 text-emerald-300 text-xs p-4 overflow-x-auto"><code>{PYTHON_EXAMPLE}</code></pre>
        </section>

        <section className="mb-10">
          <h2 className="text-2xl font-bold mb-4">Endpoints</h2>
          <div className="space-y-3">
            {ENDPOINTS.map((ep) => (
              <div key={ep.path} className="rounded-xl border border-gray-200 dark:border-gray-700 p-4">
                <div className="flex items-center gap-3 flex-wrap">
                  <span className="text-xs font-mono px-1.5 py-0.5 rounded bg-emerald-500/15 text-emerald-500 border border-emerald-500/40">
                    {ep.method}
                  </span>
                  <code className="text-sm font-mono break-all">{ep.path}</code>
                </div>
                <p className="text-sm text-gray-500 mt-2">{ep.desc}</p>
                {ep.example && (
                  <p className="text-xs mt-2">
                    <span className="text-gray-500">try: </span>
                    <a
                      href={ep.example}
                      className="text-emerald-500 hover:underline font-mono break-all"
                    >
                      {ep.example}
                    </a>
                  </p>
                )}
              </div>
            ))}
          </div>
        </section>

        <section className="mb-10">
          <h2 className="text-2xl font-bold mb-3">Sample response</h2>
          <p className="text-sm text-gray-500 mb-3">
            <code>{`${BASE}/gpu/nvidia-rtx-4090/coding.json`}</code>
          </p>
          <pre className="rounded-lg bg-gray-900 text-emerald-300 text-xs p-4 overflow-x-auto"><code>{SAMPLE_GPU_RESPONSE}</code></pre>
        </section>

        <section className="mb-10 rounded-xl border border-emerald-500/40 bg-emerald-500/5 p-5">
          <h2 className="text-xl font-bold mb-2">License & attribution</h2>
          <p className="text-sm text-gray-500">
            The dataset is licensed under{' '}
            <a
              href="https://creativecommons.org/licenses/by/4.0/"
              className="text-emerald-500 underline"
            >
              CC BY 4.0
            </a>
            . You may use it commercially, redistribute it, build derivatives —
            we ask only that you link back to{' '}
            <Link href="/" className="text-emerald-500 underline">localllm-advisor.com</Link>{' '}
            so users can find updates and methodology.
          </p>
        </section>

        <section className="mb-10">
          <h2 className="text-2xl font-bold mb-3">Stability & versioning</h2>
          <p className="text-sm text-gray-500 mb-2">
            The URL prefix <code>/api/v1/</code> is the contract. Breaking
            changes (renamed fields, removed endpoints) bump the major version
            (<code>/api/v2/</code>) and we run both for at least 6 months.
            Backwards-compatible additions (new optional fields, new endpoints)
            land on v1 without a bump.
          </p>
          <p className="text-sm text-gray-500">
            Each response carries a <code>schema</code> field (e.g.{' '}
            <code>localllm.advisor.gpu_recommendations@1.0.0</code>) so consumers
            can branch on the version if needed.
          </p>
        </section>

        <section className="mb-10">
          <h2 className="text-2xl font-bold mb-3">Methodology</h2>
          <p className="text-sm text-gray-500">
            Compatibility uses the same fitting heuristic the rest of the site
            does (largest fitting quant under 85% of VRAM). Ranking inside each
            (GPU, use case) endpoint is a benchmark-channel composite with a
            completeness penalty so partially-benchmarked models can&apos;t
            cherry-pick. Full details on the{' '}
            <Link href="/methodology" className="text-emerald-500 underline">methodology page</Link>.
          </p>
        </section>
      </main>
      <SiteFooter />
    </div>
  );
}
