#!/usr/bin/env python3
"""
Script to expand public/data/models.json with comprehensive LLM data.
Adds ~100+ models from families not yet represented or with gaps.
"""
import json, math

def vram(params_b, bpw):
    """Estimate VRAM in MB: params * bpw * 128 bytes + overhead."""
    base = round(params_b * bpw * 128)
    if params_b < 1:     overhead = 300
    elif params_b < 4:   overhead = 450
    elif params_b < 15:  overhead = 500
    elif params_b < 35:  overhead = 800
    elif params_b < 80:  overhead = 1500
    else:                overhead = 3000
    return base + overhead

def quants(params_b, ollama_base=None):
    levels = [
        ("Q4_K_M", 4.5,  0.94),
        ("Q6_K",   6.5,  0.97),
        ("Q8_0",   8.0,  0.995),
        ("FP16",   16.0, 1.0),
    ]
    result = []
    for level, bpw, quality in levels:
        entry = {
            "level": level,
            "bpw": bpw,
            "vram_mb": vram(params_b, bpw),
            "quality": quality,
        }
        if ollama_base:
            suffix = level.lower().replace("_", "_")
            entry["ollama_tag"] = f"{ollama_base}:{level.lower()}"
        result.append(entry)
    return result

def empty_benchmarks(**kwargs):
    base = {
        "humaneval": None, "mmlu_pro": None, "math": None,
        "ifeval": None, "bbh": None, "mmmu": None, "gpqa": None,
        "musr": None, "mbpp": None, "bigcodebench": None,
        "alpacaeval": None, "mmbench": None,
    }
    base.update(kwargs)
    return base

# ─────────────────────────────────────────────────────────────────────────────
# NEW MODELS
# ─────────────────────────────────────────────────────────────────────────────
NEW_MODELS = [

    # ── GPT-2 family (OpenAI, 2019, open-weight) ──────────────────────────
    {
        "id": "gpt2-124m",
        "name": "GPT-2 124M",
        "family": "gpt2",
        "params_b": 0.124,
        "architecture": "dense",
        "capabilities": ["chat"],
        "context_length": 1024,
        "release_date": "2019-02-14",
        "hf_id": "openai-community/gpt2",
        "provider": "OpenAI",
        "hf_downloads": 5000000,
        "quantizations": quants(0.124),
        "benchmarks": empty_benchmarks(),
        "gguf_sources": [{"repo": "ggml-org/gpt-2-GGUF", "provider": "ggml-org"}],
    },
    {
        "id": "gpt2-medium-345m",
        "name": "GPT-2 Medium 345M",
        "family": "gpt2",
        "params_b": 0.345,
        "architecture": "dense",
        "capabilities": ["chat"],
        "context_length": 1024,
        "release_date": "2019-02-14",
        "hf_id": "openai-community/gpt2-medium",
        "provider": "OpenAI",
        "hf_downloads": 1000000,
        "quantizations": quants(0.345),
        "benchmarks": empty_benchmarks(),
        "gguf_sources": [{"repo": "ggml-org/gpt-2-GGUF", "provider": "ggml-org"}],
    },
    {
        "id": "gpt2-large-774m",
        "name": "GPT-2 Large 774M",
        "family": "gpt2",
        "params_b": 0.774,
        "architecture": "dense",
        "capabilities": ["chat"],
        "context_length": 1024,
        "release_date": "2019-02-14",
        "hf_id": "openai-community/gpt2-large",
        "provider": "OpenAI",
        "hf_downloads": 500000,
        "quantizations": quants(0.774),
        "benchmarks": empty_benchmarks(),
    },
    {
        "id": "gpt2-xl-1.5b",
        "name": "GPT-2 XL 1.5B",
        "family": "gpt2",
        "params_b": 1.5,
        "architecture": "dense",
        "capabilities": ["chat"],
        "context_length": 1024,
        "release_date": "2019-11-05",
        "hf_id": "openai-community/gpt2-xl",
        "provider": "OpenAI",
        "hf_downloads": 800000,
        "quantizations": quants(1.5),
        "benchmarks": empty_benchmarks(),
    },

    # ── BLOOM family (BigScience, 2022) ─────────────────────────────────────
    {
        "id": "bloomz-7b",
        "name": "BLOOMZ 7B",
        "family": "bloom",
        "params_b": 7.1,
        "architecture": "dense",
        "capabilities": ["chat", "multilingual"],
        "context_length": 2048,
        "release_date": "2022-11-03",
        "hf_id": "bigscience/bloomz-7b1",
        "provider": "BigScience",
        "hf_downloads": 200000,
        "quantizations": quants(7.1),
        "benchmarks": empty_benchmarks(humaneval=15.5, mmlu_pro=None),
        "gguf_sources": [{"repo": "TheBloke/bloomz-7b1-GGUF", "provider": "TheBloke"}],
    },
    {
        "id": "bloom-176b",
        "name": "BLOOM 176B",
        "family": "bloom",
        "params_b": 176.0,
        "architecture": "dense",
        "capabilities": ["chat", "multilingual"],
        "context_length": 2048,
        "release_date": "2022-07-06",
        "hf_id": "bigscience/bloom",
        "provider": "BigScience",
        "hf_downloads": 50000,
        "quantizations": quants(176.0),
        "benchmarks": empty_benchmarks(humaneval=15.0, mmlu_pro=None),
    },

    # ── OPT family (Meta, 2022) ──────────────────────────────────────────────
    {
        "id": "opt-1.3b",
        "name": "OPT 1.3B",
        "family": "opt",
        "params_b": 1.3,
        "architecture": "dense",
        "capabilities": ["chat"],
        "context_length": 2048,
        "release_date": "2022-05-03",
        "hf_id": "facebook/opt-1.3b",
        "provider": "Meta",
        "hf_downloads": 300000,
        "quantizations": quants(1.3),
        "benchmarks": empty_benchmarks(),
        "gguf_sources": [{"repo": "TheBloke/OPT-1.3B-GGUF", "provider": "TheBloke"}],
    },
    {
        "id": "opt-2.7b",
        "name": "OPT 2.7B",
        "family": "opt",
        "params_b": 2.7,
        "architecture": "dense",
        "capabilities": ["chat"],
        "context_length": 2048,
        "release_date": "2022-05-03",
        "hf_id": "facebook/opt-2.7b",
        "provider": "Meta",
        "hf_downloads": 200000,
        "quantizations": quants(2.7),
        "benchmarks": empty_benchmarks(),
        "gguf_sources": [{"repo": "TheBloke/OPT-2.7B-GGUF", "provider": "TheBloke"}],
    },
    {
        "id": "opt-6.7b",
        "name": "OPT 6.7B",
        "family": "opt",
        "params_b": 6.7,
        "architecture": "dense",
        "capabilities": ["chat"],
        "context_length": 2048,
        "release_date": "2022-05-03",
        "hf_id": "facebook/opt-6.7b",
        "provider": "Meta",
        "hf_downloads": 150000,
        "quantizations": quants(6.7),
        "benchmarks": empty_benchmarks(humaneval=3.7),
        "gguf_sources": [{"repo": "TheBloke/OPT-6.7B-GGUF", "provider": "TheBloke"}],
    },
    {
        "id": "opt-13b",
        "name": "OPT 13B",
        "family": "opt",
        "params_b": 13.0,
        "architecture": "dense",
        "capabilities": ["chat"],
        "context_length": 2048,
        "release_date": "2022-05-03",
        "hf_id": "facebook/opt-13b",
        "provider": "Meta",
        "hf_downloads": 100000,
        "quantizations": quants(13.0),
        "benchmarks": empty_benchmarks(humaneval=5.5),
        "gguf_sources": [{"repo": "TheBloke/OPT-13B-GGUF", "provider": "TheBloke"}],
    },
    {
        "id": "opt-30b",
        "name": "OPT 30B",
        "family": "opt",
        "params_b": 30.0,
        "architecture": "dense",
        "capabilities": ["chat"],
        "context_length": 2048,
        "release_date": "2022-05-03",
        "hf_id": "facebook/opt-30b",
        "provider": "Meta",
        "hf_downloads": 60000,
        "quantizations": quants(30.0),
        "benchmarks": empty_benchmarks(),
    },
    {
        "id": "opt-66b",
        "name": "OPT 66B",
        "family": "opt",
        "params_b": 66.0,
        "architecture": "dense",
        "capabilities": ["chat"],
        "context_length": 2048,
        "release_date": "2022-05-03",
        "hf_id": "facebook/opt-66b",
        "provider": "Meta",
        "hf_downloads": 40000,
        "quantizations": quants(66.0),
        "benchmarks": empty_benchmarks(),
    },

    # ── MPT family (MosaicML, 2023) ──────────────────────────────────────────
    {
        "id": "mpt-7b",
        "name": "MPT-7B",
        "family": "mpt",
        "params_b": 7.0,
        "architecture": "dense",
        "capabilities": ["chat"],
        "context_length": 65536,
        "release_date": "2023-05-05",
        "hf_id": "mosaicml/mpt-7b-instruct",
        "provider": "MosaicML",
        "hf_downloads": 200000,
        "quantizations": quants(7.0),
        "benchmarks": empty_benchmarks(humaneval=18.3),
        "gguf_sources": [{"repo": "TheBloke/mpt-7b-instruct-GGUF", "provider": "TheBloke"}],
    },
    {
        "id": "mpt-30b",
        "name": "MPT-30B",
        "family": "mpt",
        "params_b": 30.0,
        "architecture": "dense",
        "capabilities": ["chat"],
        "context_length": 8192,
        "release_date": "2023-06-22",
        "hf_id": "mosaicml/mpt-30b-instruct",
        "provider": "MosaicML",
        "hf_downloads": 80000,
        "quantizations": quants(30.0),
        "benchmarks": empty_benchmarks(humaneval=26.8),
        "gguf_sources": [{"repo": "TheBloke/mpt-30B-instruct-GGUF", "provider": "TheBloke"}],
    },

    # ── Dolly family (Databricks, 2023) ──────────────────────────────────────
    {
        "id": "dolly-v2-3b",
        "name": "Dolly v2 3B",
        "family": "dolly",
        "params_b": 2.8,
        "architecture": "dense",
        "capabilities": ["chat"],
        "context_length": 2048,
        "release_date": "2023-04-12",
        "hf_id": "databricks/dolly-v2-3b",
        "provider": "Databricks",
        "hf_downloads": 100000,
        "quantizations": quants(2.8),
        "benchmarks": empty_benchmarks(),
        "gguf_sources": [{"repo": "TheBloke/dolly-v2-3b-GGUF", "provider": "TheBloke"}],
    },
    {
        "id": "dolly-v2-7b",
        "name": "Dolly v2 7B",
        "family": "dolly",
        "params_b": 6.9,
        "architecture": "dense",
        "capabilities": ["chat"],
        "context_length": 2048,
        "release_date": "2023-04-12",
        "hf_id": "databricks/dolly-v2-7b",
        "provider": "Databricks",
        "hf_downloads": 80000,
        "quantizations": quants(6.9),
        "benchmarks": empty_benchmarks(),
        "gguf_sources": [{"repo": "TheBloke/dolly-v2-7b-GGUF", "provider": "TheBloke"}],
    },
    {
        "id": "dolly-v2-12b",
        "name": "Dolly v2 12B",
        "family": "dolly",
        "params_b": 12.0,
        "architecture": "dense",
        "capabilities": ["chat"],
        "context_length": 2048,
        "release_date": "2023-04-12",
        "hf_id": "databricks/dolly-v2-12b",
        "provider": "Databricks",
        "hf_downloads": 60000,
        "quantizations": quants(12.0),
        "benchmarks": empty_benchmarks(),
        "gguf_sources": [{"repo": "TheBloke/dolly-v2-12b-GGUF", "provider": "TheBloke"}],
    },

    # ── Alpaca (Stanford, 2023) ───────────────────────────────────────────────
    {
        "id": "alpaca-7b",
        "name": "Alpaca 7B",
        "family": "alpaca",
        "params_b": 7.0,
        "architecture": "dense",
        "capabilities": ["chat"],
        "context_length": 2048,
        "release_date": "2023-03-13",
        "hf_id": "tatsu-lab/alpaca-7b-wdiff",
        "provider": "Stanford",
        "hf_downloads": 50000,
        "quantizations": quants(7.0),
        "benchmarks": empty_benchmarks(),
    },

    # ── LLaVA family (vision, 2023-2024) ────────────────────────────────────
    {
        "id": "llava-1.5-7b",
        "name": "LLaVA-1.5 7B",
        "family": "llava",
        "params_b": 7.1,
        "architecture": "dense",
        "capabilities": ["chat", "vision"],
        "context_length": 4096,
        "release_date": "2023-10-05",
        "hf_id": "llava-hf/llava-1.5-7b-hf",
        "provider": "LLaVA",
        "hf_downloads": 500000,
        "ollama_base": "llava:7b",
        "quantizations": quants(7.1, "llava:7b"),
        "benchmarks": empty_benchmarks(mmbench=64.3, mmmu=34.8),
        "gguf_sources": [{"repo": "mys/ggml_llava-v1.5-7b", "provider": "mys"}],
    },
    {
        "id": "llava-1.5-13b",
        "name": "LLaVA-1.5 13B",
        "family": "llava",
        "params_b": 13.1,
        "architecture": "dense",
        "capabilities": ["chat", "vision"],
        "context_length": 4096,
        "release_date": "2023-10-05",
        "hf_id": "llava-hf/llava-1.5-13b-hf",
        "provider": "LLaVA",
        "hf_downloads": 300000,
        "ollama_base": "llava:13b",
        "quantizations": quants(13.1, "llava:13b"),
        "benchmarks": empty_benchmarks(mmbench=67.7, mmmu=36.4),
        "gguf_sources": [{"repo": "mys/ggml_llava-v1.5-13b", "provider": "mys"}],
    },
    {
        "id": "llava-1.6-mistral-7b",
        "name": "LLaVA-1.6 Mistral 7B",
        "family": "llava",
        "params_b": 7.2,
        "architecture": "dense",
        "capabilities": ["chat", "vision"],
        "context_length": 8192,
        "release_date": "2024-01-30",
        "hf_id": "llava-hf/llava-v1.6-mistral-7b-hf",
        "provider": "LLaVA",
        "hf_downloads": 400000,
        "ollama_base": "llava:7b-v1.6",
        "quantizations": quants(7.2, "llava:7b-v1.6"),
        "benchmarks": empty_benchmarks(mmbench=67.7, mmmu=35.4),
        "gguf_sources": [{"repo": "cjpais/llava-1.6-mistral-7b-gguf", "provider": "cjpais"}],
    },
    {
        "id": "llava-1.6-34b",
        "name": "LLaVA-1.6 34B",
        "family": "llava",
        "params_b": 34.4,
        "architecture": "dense",
        "capabilities": ["chat", "vision"],
        "context_length": 8192,
        "release_date": "2024-01-30",
        "hf_id": "llava-hf/llava-v1.6-34b-hf",
        "provider": "LLaVA",
        "hf_downloads": 100000,
        "ollama_base": "llava:34b",
        "quantizations": quants(34.4, "llava:34b"),
        "benchmarks": empty_benchmarks(mmbench=79.3, mmmu=51.1),
        "gguf_sources": [{"repo": "cjpais/llava-v1.6-34B-gguf", "provider": "cjpais"}],
    },

    # ── Moondream (vikhyatk, 2024) ───────────────────────────────────────────
    {
        "id": "moondream2-1.9b",
        "name": "Moondream 2 1.9B",
        "family": "moondream",
        "params_b": 1.87,
        "architecture": "dense",
        "capabilities": ["chat", "vision"],
        "context_length": 2048,
        "release_date": "2024-03-05",
        "hf_id": "vikhyatk/moondream2",
        "provider": "Moondream",
        "hf_downloads": 200000,
        "ollama_base": "moondream",
        "quantizations": quants(1.87, "moondream"),
        "benchmarks": empty_benchmarks(mmbench=51.1),
    },

    # ── SmolLM2 (HuggingFace, 2024) ──────────────────────────────────────────
    {
        "id": "smollm2-135m",
        "name": "SmolLM2 135M",
        "family": "smollm",
        "params_b": 0.135,
        "architecture": "dense",
        "capabilities": ["chat"],
        "context_length": 2048,
        "release_date": "2024-11-21",
        "hf_id": "HuggingFaceTB/SmolLM2-135M-Instruct",
        "provider": "HuggingFace",
        "hf_downloads": 100000,
        "quantizations": quants(0.135),
        "benchmarks": empty_benchmarks(),
        "gguf_sources": [{"repo": "HuggingFaceTB/SmolLM2-135M-Instruct-GGUF", "provider": "HuggingFace"}],
    },
    {
        "id": "smollm2-360m",
        "name": "SmolLM2 360M",
        "family": "smollm",
        "params_b": 0.360,
        "architecture": "dense",
        "capabilities": ["chat"],
        "context_length": 8192,
        "release_date": "2024-11-21",
        "hf_id": "HuggingFaceTB/SmolLM2-360M-Instruct",
        "provider": "HuggingFace",
        "hf_downloads": 150000,
        "quantizations": quants(0.360),
        "benchmarks": empty_benchmarks(),
        "gguf_sources": [{"repo": "HuggingFaceTB/SmolLM2-360M-Instruct-GGUF", "provider": "HuggingFace"}],
    },
    {
        "id": "smollm2-1.7b",
        "name": "SmolLM2 1.7B",
        "family": "smollm",
        "params_b": 1.71,
        "architecture": "dense",
        "capabilities": ["chat"],
        "context_length": 8192,
        "release_date": "2024-11-21",
        "hf_id": "HuggingFaceTB/SmolLM2-1.7B-Instruct",
        "provider": "HuggingFace",
        "hf_downloads": 400000,
        "ollama_base": "smollm2:1.7b",
        "quantizations": quants(1.71, "smollm2:1.7b"),
        "benchmarks": empty_benchmarks(humaneval=22.0, ifeval=55.0),
        "gguf_sources": [{"repo": "HuggingFaceTB/SmolLM2-1.7B-Instruct-GGUF", "provider": "HuggingFace"}],
    },

    # ── StableLM additions (Stability AI) ────────────────────────────────────
    {
        "id": "stablelm-zephyr-3b",
        "name": "StableLM Zephyr 3B",
        "family": "stablelm",
        "params_b": 2.79,
        "architecture": "dense",
        "capabilities": ["chat"],
        "context_length": 4096,
        "release_date": "2023-11-03",
        "hf_id": "stabilityai/stablelm-zephyr-3b",
        "provider": "Stability AI",
        "hf_downloads": 100000,
        "ollama_base": "stablelm-zephyr:3b",
        "quantizations": quants(2.79, "stablelm-zephyr:3b"),
        "benchmarks": empty_benchmarks(ifeval=52.0),
        "gguf_sources": [{"repo": "bartowski/stablelm-zephyr-3b-GGUF", "provider": "bartowski"}],
    },
    {
        "id": "stablelm-2-12b",
        "name": "StableLM 2 12B",
        "family": "stablelm",
        "params_b": 12.0,
        "architecture": "dense",
        "capabilities": ["chat"],
        "context_length": 4096,
        "release_date": "2024-03-22",
        "hf_id": "stabilityai/stablelm-2-12b-chat",
        "provider": "Stability AI",
        "hf_downloads": 50000,
        "quantizations": quants(12.0),
        "benchmarks": empty_benchmarks(humaneval=35.0, ifeval=54.0),
        "gguf_sources": [{"repo": "bartowski/stablelm-2-12b-chat-GGUF", "provider": "bartowski"}],
    },

    # ── Falcon additions (TII) ───────────────────────────────────────────────
    {
        "id": "falcon-40b",
        "name": "Falcon 40B",
        "family": "falcon",
        "params_b": 40.0,
        "architecture": "dense",
        "capabilities": ["chat"],
        "context_length": 8192,
        "release_date": "2023-05-25",
        "hf_id": "tiiuae/falcon-40b-instruct",
        "provider": "TII",
        "hf_downloads": 200000,
        "quantizations": quants(40.0),
        "benchmarks": empty_benchmarks(humaneval=24.4, mmlu_pro=33.0, bbh=52.0, ifeval=27.0),
        "gguf_sources": [{"repo": "TheBloke/falcon-40b-instruct-GGUF", "provider": "TheBloke"}],
    },
    {
        "id": "falcon-180b",
        "name": "Falcon 180B",
        "family": "falcon",
        "params_b": 180.0,
        "architecture": "dense",
        "capabilities": ["chat"],
        "context_length": 8192,
        "release_date": "2023-09-06",
        "hf_id": "tiiuae/falcon-180B-chat",
        "provider": "TII",
        "hf_downloads": 50000,
        "quantizations": quants(180.0),
        "benchmarks": empty_benchmarks(humaneval=54.0, mmlu_pro=45.0, bbh=65.0, ifeval=41.0),
        "gguf_sources": [{"repo": "TheBloke/Falcon-180B-GGUF", "provider": "TheBloke"}],
    },
    {
        "id": "falcon2-11b",
        "name": "Falcon2 11B",
        "family": "falcon",
        "params_b": 11.0,
        "architecture": "dense",
        "capabilities": ["chat"],
        "context_length": 8192,
        "release_date": "2024-05-15",
        "hf_id": "tiiuae/falcon-11B",
        "provider": "TII",
        "hf_downloads": 80000,
        "quantizations": quants(11.0),
        "benchmarks": empty_benchmarks(humaneval=46.3, mmlu_pro=34.0, ifeval=55.0),
        "gguf_sources": [{"repo": "bartowski/falcon-11B-GGUF", "provider": "bartowski"}],
    },
    {
        "id": "falcon3-1b",
        "name": "Falcon3-1B",
        "family": "falcon",
        "params_b": 1.0,
        "architecture": "dense",
        "capabilities": ["chat"],
        "context_length": 32768,
        "release_date": "2024-11-29",
        "hf_id": "tiiuae/Falcon3-1B-Instruct",
        "provider": "TII",
        "hf_downloads": 30000,
        "quantizations": quants(1.0),
        "benchmarks": empty_benchmarks(ifeval=42.0),
        "gguf_sources": [{"repo": "bartowski/Falcon3-1B-Instruct-GGUF", "provider": "bartowski"}],
    },
    {
        "id": "falcon3-3b",
        "name": "Falcon3-3B",
        "family": "falcon",
        "params_b": 3.1,
        "architecture": "dense",
        "capabilities": ["chat"],
        "context_length": 32768,
        "release_date": "2024-11-29",
        "hf_id": "tiiuae/Falcon3-3B-Instruct",
        "provider": "TII",
        "hf_downloads": 40000,
        "quantizations": quants(3.1),
        "benchmarks": empty_benchmarks(humaneval=38.0, ifeval=52.0),
        "gguf_sources": [{"repo": "bartowski/Falcon3-3B-Instruct-GGUF", "provider": "bartowski"}],
    },
    {
        "id": "falcon3-10b",
        "name": "Falcon3-10B",
        "family": "falcon",
        "params_b": 10.3,
        "architecture": "dense",
        "capabilities": ["chat"],
        "context_length": 32768,
        "release_date": "2024-11-29",
        "hf_id": "tiiuae/Falcon3-10B-Instruct",
        "provider": "TII",
        "hf_downloads": 60000,
        "quantizations": quants(10.3),
        "benchmarks": empty_benchmarks(humaneval=62.0, ifeval=68.0, mmlu_pro=40.0),
        "gguf_sources": [{"repo": "bartowski/Falcon3-10B-Instruct-GGUF", "provider": "bartowski"}],
    },

    # ── InternLM additions (Shanghai AI Lab) ─────────────────────────────────
    {
        "id": "internlm2-1b",
        "name": "InternLM2 1B",
        "family": "internlm",
        "params_b": 1.0,
        "architecture": "dense",
        "capabilities": ["chat"],
        "context_length": 32768,
        "release_date": "2024-01-17",
        "hf_id": "internlm/internlm2-chat-1_8b",
        "provider": "Shanghai AI Lab",
        "hf_downloads": 50000,
        "quantizations": quants(1.0),
        "benchmarks": empty_benchmarks(),
        "gguf_sources": [{"repo": "bartowski/internlm2_5-1_8b-chat-GGUF", "provider": "bartowski"}],
    },
    {
        "id": "internlm2-5b",
        "name": "InternLM2 5B",
        "family": "internlm",
        "params_b": 4.5,
        "architecture": "dense",
        "capabilities": ["chat"],
        "context_length": 32768,
        "release_date": "2024-01-17",
        "hf_id": "internlm/internlm2-chat-5b",
        "provider": "Shanghai AI Lab",
        "hf_downloads": 40000,
        "quantizations": quants(4.5),
        "benchmarks": empty_benchmarks(humaneval=47.6),
        "gguf_sources": [{"repo": "TheBloke/internlm2-chat-5B-GGUF", "provider": "TheBloke"}],
    },
    {
        "id": "internlm2-20b",
        "name": "InternLM2 20B",
        "family": "internlm",
        "params_b": 19.8,
        "architecture": "dense",
        "capabilities": ["chat", "coding"],
        "context_length": 32768,
        "release_date": "2024-01-17",
        "hf_id": "internlm/internlm2-chat-20b",
        "provider": "Shanghai AI Lab",
        "hf_downloads": 60000,
        "quantizations": quants(19.8),
        "benchmarks": empty_benchmarks(humaneval=57.6, mmlu_pro=45.0, math=52.0, ifeval=72.0),
        "gguf_sources": [{"repo": "bartowski/internlm2-chat-20b-GGUF", "provider": "bartowski"}],
    },
    {
        "id": "internlm2.5-7b",
        "name": "InternLM2.5 7B",
        "family": "internlm",
        "params_b": 7.74,
        "architecture": "dense",
        "capabilities": ["chat", "coding", "reasoning"],
        "context_length": 1048576,
        "release_date": "2024-08-05",
        "hf_id": "internlm/internlm2_5-7b-chat",
        "provider": "Shanghai AI Lab",
        "hf_downloads": 150000,
        "quantizations": quants(7.74),
        "benchmarks": empty_benchmarks(humaneval=67.2, mmlu_pro=46.0, math=62.0, ifeval=71.0),
        "gguf_sources": [{"repo": "bartowski/internlm2_5-7b-chat-GGUF", "provider": "bartowski"}],
    },
    {
        "id": "internlm2.5-20b",
        "name": "InternLM2.5 20B",
        "family": "internlm",
        "params_b": 19.8,
        "architecture": "dense",
        "capabilities": ["chat", "coding", "reasoning"],
        "context_length": 1048576,
        "release_date": "2024-08-05",
        "hf_id": "internlm/internlm2_5-20b-chat",
        "provider": "Shanghai AI Lab",
        "hf_downloads": 80000,
        "quantizations": quants(19.8),
        "benchmarks": empty_benchmarks(humaneval=72.0, mmlu_pro=52.0, math=68.0, ifeval=75.0),
        "gguf_sources": [{"repo": "bartowski/internlm2_5-20b-chat-GGUF", "provider": "bartowski"}],
    },

    # ── Baichuan family (Baichuan AI) ────────────────────────────────────────
    {
        "id": "baichuan2-7b",
        "name": "Baichuan2 7B",
        "family": "baichuan",
        "params_b": 7.0,
        "architecture": "dense",
        "capabilities": ["chat", "multilingual"],
        "context_length": 4096,
        "release_date": "2023-09-06",
        "hf_id": "baichuan-inc/Baichuan2-7B-Chat",
        "provider": "Baichuan AI",
        "hf_downloads": 100000,
        "quantizations": quants(7.0),
        "benchmarks": empty_benchmarks(humaneval=18.3, math=24.6),
        "gguf_sources": [{"repo": "TheBloke/Baichuan2-7B-Chat-GGUF", "provider": "TheBloke"}],
    },
    {
        "id": "baichuan2-13b",
        "name": "Baichuan2 13B",
        "family": "baichuan",
        "params_b": 13.0,
        "architecture": "dense",
        "capabilities": ["chat", "multilingual"],
        "context_length": 4096,
        "release_date": "2023-09-06",
        "hf_id": "baichuan-inc/Baichuan2-13B-Chat",
        "provider": "Baichuan AI",
        "hf_downloads": 80000,
        "quantizations": quants(13.0),
        "benchmarks": empty_benchmarks(humaneval=17.1, math=30.0),
        "gguf_sources": [{"repo": "TheBloke/Baichuan2-13B-Chat-GGUF", "provider": "TheBloke"}],
    },

    # ── ChatGLM family (Tsinghua/Zhipu AI) ───────────────────────────────────
    {
        "id": "chatglm2-6b",
        "name": "ChatGLM2 6B",
        "family": "chatglm",
        "params_b": 6.24,
        "architecture": "dense",
        "capabilities": ["chat", "multilingual"],
        "context_length": 32768,
        "release_date": "2023-06-25",
        "hf_id": "THUDM/chatglm2-6b",
        "provider": "Tsinghua/Zhipu AI",
        "hf_downloads": 500000,
        "quantizations": quants(6.24),
        "benchmarks": empty_benchmarks(humaneval=20.7),
        "gguf_sources": [{"repo": "TheBloke/chatglm2-6B-GGUF", "provider": "TheBloke"}],
    },
    {
        "id": "chatglm3-6b",
        "name": "ChatGLM3 6B",
        "family": "chatglm",
        "params_b": 6.24,
        "architecture": "dense",
        "capabilities": ["chat", "coding", "multilingual"],
        "context_length": 131072,
        "release_date": "2023-10-27",
        "hf_id": "THUDM/chatglm3-6b",
        "provider": "Tsinghua/Zhipu AI",
        "hf_downloads": 600000,
        "quantizations": quants(6.24),
        "benchmarks": empty_benchmarks(humaneval=42.7),
        "gguf_sources": [{"repo": "TheBloke/chatglm3-6B-GGUF", "provider": "TheBloke"}],
    },

    # ── Yi-1.5 family (01.AI) ────────────────────────────────────────────────
    {
        "id": "yi-1.5-6b",
        "name": "Yi-1.5 6B",
        "family": "yi",
        "params_b": 6.06,
        "architecture": "dense",
        "capabilities": ["chat"],
        "context_length": 4096,
        "release_date": "2024-05-13",
        "hf_id": "01-ai/Yi-1.5-6B-Chat",
        "provider": "01.AI",
        "hf_downloads": 80000,
        "quantizations": quants(6.06),
        "benchmarks": empty_benchmarks(humaneval=38.0, math=45.0),
        "gguf_sources": [{"repo": "bartowski/Yi-1.5-6B-Chat-GGUF", "provider": "bartowski"}],
    },
    {
        "id": "yi-1.5-9b",
        "name": "Yi-1.5 9B",
        "family": "yi",
        "params_b": 9.0,
        "architecture": "dense",
        "capabilities": ["chat"],
        "context_length": 4096,
        "release_date": "2024-05-13",
        "hf_id": "01-ai/Yi-1.5-9B-Chat",
        "provider": "01.AI",
        "hf_downloads": 100000,
        "quantizations": quants(9.0),
        "benchmarks": empty_benchmarks(humaneval=45.0, math=52.0),
        "gguf_sources": [{"repo": "bartowski/Yi-1.5-9B-Chat-GGUF", "provider": "bartowski"}],
    },
    {
        "id": "yi-1.5-34b",
        "name": "Yi-1.5 34B",
        "family": "yi",
        "params_b": 34.4,
        "architecture": "dense",
        "capabilities": ["chat"],
        "context_length": 4096,
        "release_date": "2024-05-13",
        "hf_id": "01-ai/Yi-1.5-34B-Chat",
        "provider": "01.AI",
        "hf_downloads": 120000,
        "quantizations": quants(34.4),
        "benchmarks": empty_benchmarks(humaneval=66.0, math=77.0, mmlu_pro=52.0),
        "gguf_sources": [{"repo": "bartowski/Yi-1.5-34B-Chat-GGUF", "provider": "bartowski"}],
    },

    # ── Command additions (Cohere) ───────────────────────────────────────────
    {
        "id": "command-r-plus-104b",
        "name": "Command-R+ 104B",
        "family": "command",
        "params_b": 104.0,
        "architecture": "dense",
        "capabilities": ["chat", "reasoning"],
        "context_length": 131072,
        "release_date": "2024-04-04",
        "hf_id": "CohereForAI/c4ai-command-r-plus",
        "provider": "Cohere",
        "hf_downloads": 50000,
        "quantizations": quants(104.0),
        "benchmarks": empty_benchmarks(humaneval=81.0, mmlu_pro=56.0, math=47.2, ifeval=85.4, bbh=74.0),
        "gguf_sources": [{"repo": "bartowski/c4ai-command-r-plus-GGUF", "provider": "bartowski"}],
    },
    {
        "id": "command-r7b",
        "name": "Command-R7B",
        "family": "command",
        "params_b": 7.0,
        "architecture": "dense",
        "capabilities": ["chat", "reasoning"],
        "context_length": 131072,
        "release_date": "2024-12-13",
        "hf_id": "CohereForAI/c4ai-command-r7b-12-2024",
        "provider": "Cohere",
        "hf_downloads": 40000,
        "quantizations": quants(7.0),
        "benchmarks": empty_benchmarks(humaneval=54.0, mmlu_pro=38.0, ifeval=71.0),
        "gguf_sources": [{"repo": "bartowski/c4ai-command-r7b-12-2024-GGUF", "provider": "bartowski"}],
    },

    # ── Aya Expanse (Cohere, 2024) ───────────────────────────────────────────
    {
        "id": "aya-expanse-8b",
        "name": "Aya Expanse 8B",
        "family": "aya",
        "params_b": 8.0,
        "architecture": "dense",
        "capabilities": ["chat", "multilingual"],
        "context_length": 131072,
        "release_date": "2024-10-30",
        "hf_id": "CohereForAI/aya-expanse-8b",
        "provider": "Cohere",
        "hf_downloads": 60000,
        "quantizations": quants(8.0),
        "benchmarks": empty_benchmarks(humaneval=45.0, mmlu_pro=36.0, ifeval=65.0),
        "gguf_sources": [{"repo": "bartowski/aya-expanse-8b-GGUF", "provider": "bartowski"}],
    },
    {
        "id": "aya-expanse-32b",
        "name": "Aya Expanse 32B",
        "family": "aya",
        "params_b": 32.0,
        "architecture": "dense",
        "capabilities": ["chat", "multilingual"],
        "context_length": 131072,
        "release_date": "2024-10-30",
        "hf_id": "CohereForAI/aya-expanse-32b",
        "provider": "Cohere",
        "hf_downloads": 40000,
        "quantizations": quants(32.0),
        "benchmarks": empty_benchmarks(humaneval=62.0, mmlu_pro=46.0, ifeval=73.0),
        "gguf_sources": [{"repo": "bartowski/aya-expanse-32b-GGUF", "provider": "bartowski"}],
    },

    # ── DBRX (Databricks, 2024) ───────────────────────────────────────────────
    {
        "id": "dbrx-132b",
        "name": "DBRX 132B",
        "family": "dbrx",
        "params_b": 132.0,
        "architecture": "moe",
        "capabilities": ["chat", "coding"],
        "context_length": 32768,
        "release_date": "2024-03-27",
        "hf_id": "databricks/dbrx-instruct",
        "provider": "Databricks",
        "hf_downloads": 30000,
        "quantizations": quants(132.0),
        "benchmarks": empty_benchmarks(humaneval=70.1, mmlu_pro=45.0, math=66.9, ifeval=62.0, bbh=56.0),
        "gguf_sources": [{"repo": "bartowski/dbrx-instruct-GGUF", "provider": "bartowski"}],
    },

    # ── Jamba (AI21 Labs, 2024) ───────────────────────────────────────────────
    {
        "id": "jamba-1.5-mini-52b",
        "name": "Jamba 1.5 Mini 52B",
        "family": "jamba",
        "params_b": 51.6,
        "architecture": "moe",
        "capabilities": ["chat", "reasoning"],
        "context_length": 262144,
        "release_date": "2024-08-22",
        "hf_id": "ai21labs/AI21-Jamba-1.5-Mini",
        "provider": "AI21 Labs",
        "hf_downloads": 20000,
        "quantizations": quants(51.6),
        "benchmarks": empty_benchmarks(humaneval=64.0, mmlu_pro=42.0, math=57.0, ifeval=64.0),
        "gguf_sources": [{"repo": "bartowski/AI21-Jamba-1.5-Mini-GGUF", "provider": "bartowski"}],
    },

    # ── WizardLM additions (Microsoft) ──────────────────────────────────────
    {
        "id": "wizardlm-7b",
        "name": "WizardLM 7B",
        "family": "wizardlm",
        "params_b": 7.0,
        "architecture": "dense",
        "capabilities": ["chat"],
        "context_length": 2048,
        "release_date": "2023-05-26",
        "hf_id": "WizardLMTeam/WizardLM-7B-V1.0",
        "provider": "Microsoft",
        "hf_downloads": 100000,
        "quantizations": quants(7.0),
        "benchmarks": empty_benchmarks(humaneval=19.1),
        "gguf_sources": [{"repo": "TheBloke/WizardLM-7B-V1.0-Uncensored-GGUF", "provider": "TheBloke"}],
    },
    {
        "id": "wizardlm-13b",
        "name": "WizardLM 13B",
        "family": "wizardlm",
        "params_b": 13.0,
        "architecture": "dense",
        "capabilities": ["chat"],
        "context_length": 4096,
        "release_date": "2023-07-03",
        "hf_id": "WizardLMTeam/WizardLM-13B-V1.2",
        "provider": "Microsoft",
        "hf_downloads": 80000,
        "quantizations": quants(13.0),
        "benchmarks": empty_benchmarks(humaneval=24.4),
        "gguf_sources": [{"repo": "TheBloke/WizardLM-13B-V1.2-GGUF", "provider": "TheBloke"}],
    },
    {
        "id": "wizardlm-70b",
        "name": "WizardLM 70B",
        "family": "wizardlm",
        "params_b": 70.0,
        "architecture": "dense",
        "capabilities": ["chat"],
        "context_length": 8192,
        "release_date": "2023-08-11",
        "hf_id": "WizardLMTeam/WizardLM-70B-V1.0",
        "provider": "Microsoft",
        "hf_downloads": 60000,
        "quantizations": quants(70.0),
        "benchmarks": empty_benchmarks(humaneval=50.6, mmlu_pro=42.0),
        "gguf_sources": [{"repo": "TheBloke/WizardLM-70B-V1.0-GGUF", "provider": "TheBloke"}],
    },

    # ── WizardCoder (Microsoft) ───────────────────────────────────────────────
    {
        "id": "wizardcoder-python-7b",
        "name": "WizardCoder Python 7B",
        "family": "wizardcoder",
        "params_b": 7.0,
        "architecture": "dense",
        "capabilities": ["coding"],
        "context_length": 4096,
        "release_date": "2023-08-26",
        "hf_id": "WizardLMTeam/WizardCoder-Python-7B-V1.0",
        "provider": "Microsoft",
        "hf_downloads": 80000,
        "quantizations": quants(7.0),
        "benchmarks": empty_benchmarks(humaneval=55.5, mbpp=51.8),
        "gguf_sources": [{"repo": "TheBloke/WizardCoder-Python-7B-V1.0-GGUF", "provider": "TheBloke"}],
    },
    {
        "id": "wizardcoder-python-13b",
        "name": "WizardCoder Python 13B",
        "family": "wizardcoder",
        "params_b": 13.0,
        "architecture": "dense",
        "capabilities": ["coding"],
        "context_length": 4096,
        "release_date": "2023-08-26",
        "hf_id": "WizardLMTeam/WizardCoder-Python-13B-V1.0",
        "provider": "Microsoft",
        "hf_downloads": 50000,
        "quantizations": quants(13.0),
        "benchmarks": empty_benchmarks(humaneval=62.2, mbpp=58.0),
        "gguf_sources": [{"repo": "TheBloke/WizardCoder-Python-13B-V1.0-GGUF", "provider": "TheBloke"}],
    },
    {
        "id": "wizardcoder-python-34b",
        "name": "WizardCoder Python 34B",
        "family": "wizardcoder",
        "params_b": 34.0,
        "architecture": "dense",
        "capabilities": ["coding"],
        "context_length": 16384,
        "release_date": "2023-08-26",
        "hf_id": "WizardLMTeam/WizardCoder-Python-34B-V1.0",
        "provider": "Microsoft",
        "hf_downloads": 60000,
        "quantizations": quants(34.0),
        "benchmarks": empty_benchmarks(humaneval=73.2, mbpp=73.1),
        "gguf_sources": [{"repo": "TheBloke/WizardCoder-Python-34B-V1.0-GGUF", "provider": "TheBloke"}],
    },

    # ── Codestral (Mistral, 2024) ─────────────────────────────────────────────
    {
        "id": "codestral-22b",
        "name": "Codestral 22B",
        "family": "mistral",
        "params_b": 22.2,
        "architecture": "dense",
        "capabilities": ["coding"],
        "context_length": 32768,
        "release_date": "2024-05-29",
        "hf_id": "mistralai/Codestral-22B-v0.1",
        "provider": "Mistral AI",
        "hf_downloads": 200000,
        "quantizations": quants(22.2),
        "benchmarks": empty_benchmarks(humaneval=81.1, mbpp=78.2, bigcodebench=52.0),
        "gguf_sources": [{"repo": "bartowski/Codestral-22B-v0.1-GGUF", "provider": "bartowski"}],
    },

    # ── MathStral (Mistral, 2024) ─────────────────────────────────────────────
    {
        "id": "mathstral-7b",
        "name": "MathStral 7B",
        "family": "mistral",
        "params_b": 7.25,
        "architecture": "dense",
        "capabilities": ["math", "reasoning"],
        "context_length": 32768,
        "release_date": "2024-07-16",
        "hf_id": "mistralai/mathstral-7B-v0.1",
        "provider": "Mistral AI",
        "hf_downloads": 80000,
        "quantizations": quants(7.25),
        "benchmarks": empty_benchmarks(humaneval=64.0, math=56.7),
        "gguf_sources": [{"repo": "bartowski/mathstral-7B-v0.1-GGUF", "provider": "bartowski"}],
    },

    # ── Pixtral (Mistral, 2024) ───────────────────────────────────────────────
    {
        "id": "pixtral-12b",
        "name": "Pixtral 12B",
        "family": "mistral",
        "params_b": 12.0,
        "architecture": "dense",
        "capabilities": ["chat", "vision"],
        "context_length": 131072,
        "release_date": "2024-09-11",
        "hf_id": "mistralai/Pixtral-12B-2409",
        "provider": "Mistral AI",
        "hf_downloads": 100000,
        "quantizations": quants(12.0),
        "benchmarks": empty_benchmarks(mmbench=72.7, mmmu=52.5, humaneval=72.0, ifeval=72.0),
        "gguf_sources": [{"repo": "bartowski/pixtral-12b-2409-GGUF", "provider": "bartowski"}],
    },

    # ── Devstral (Mistral, 2025) ──────────────────────────────────────────────
    {
        "id": "devstral-small-22b",
        "name": "Devstral Small 22B",
        "family": "mistral",
        "params_b": 22.2,
        "architecture": "dense",
        "capabilities": ["coding"],
        "context_length": 131072,
        "release_date": "2025-05-07",
        "hf_id": "mistralai/Devstral-Small-2505",
        "provider": "Mistral AI",
        "hf_downloads": 50000,
        "quantizations": quants(22.2),
        "benchmarks": empty_benchmarks(humaneval=72.0, mbpp=74.0),
        "gguf_sources": [{"repo": "bartowski/Devstral-Small-2505-GGUF", "provider": "bartowski"}],
    },

    # ── Pixtral Large (Mistral, 2024) ─────────────────────────────────────────
    {
        "id": "pixtral-large-124b",
        "name": "Pixtral Large 124B",
        "family": "mistral",
        "params_b": 124.0,
        "architecture": "dense",
        "capabilities": ["chat", "vision", "reasoning"],
        "context_length": 131072,
        "release_date": "2024-11-18",
        "hf_id": "mistralai/Pixtral-Large-Instruct-2411",
        "provider": "Mistral AI",
        "hf_downloads": 20000,
        "quantizations": quants(124.0),
        "benchmarks": empty_benchmarks(mmbench=79.0, mmmu=62.7, humaneval=82.0, ifeval=87.0),
        "gguf_sources": [{"repo": "bartowski/Pixtral-Large-Instruct-2411-GGUF", "provider": "bartowski"}],
    },

    # ── Granite additions (IBM) ───────────────────────────────────────────────
    {
        "id": "granite-3.0-2b",
        "name": "Granite 3.0 2B",
        "family": "granite",
        "params_b": 2.0,
        "architecture": "dense",
        "capabilities": ["chat", "coding"],
        "context_length": 131072,
        "release_date": "2024-09-25",
        "hf_id": "ibm-granite/granite-3.0-2b-instruct",
        "provider": "IBM",
        "hf_downloads": 40000,
        "quantizations": quants(2.0),
        "benchmarks": empty_benchmarks(humaneval=32.0, ifeval=55.0),
        "gguf_sources": [{"repo": "bartowski/granite-3.0-2b-instruct-GGUF", "provider": "bartowski"}],
    },
    {
        "id": "granite-3.0-8b",
        "name": "Granite 3.0 8B",
        "family": "granite",
        "params_b": 8.17,
        "architecture": "dense",
        "capabilities": ["chat", "coding"],
        "context_length": 131072,
        "release_date": "2024-09-25",
        "hf_id": "ibm-granite/granite-3.0-8b-instruct",
        "provider": "IBM",
        "hf_downloads": 60000,
        "quantizations": quants(8.17),
        "benchmarks": empty_benchmarks(humaneval=57.0, ifeval=76.0, mmlu_pro=38.0),
        "gguf_sources": [{"repo": "bartowski/granite-3.0-8b-instruct-GGUF", "provider": "bartowski"}],
    },
    {
        "id": "granite-3.1-2b",
        "name": "Granite 3.1 2B",
        "family": "granite",
        "params_b": 2.0,
        "architecture": "dense",
        "capabilities": ["chat", "coding"],
        "context_length": 131072,
        "release_date": "2024-12-16",
        "hf_id": "ibm-granite/granite-3.1-2b-instruct",
        "provider": "IBM",
        "hf_downloads": 30000,
        "quantizations": quants(2.0),
        "benchmarks": empty_benchmarks(humaneval=35.0, ifeval=58.0),
        "gguf_sources": [{"repo": "bartowski/granite-3.1-2b-instruct-GGUF", "provider": "bartowski"}],
    },
    {
        "id": "granite-3.1-8b",
        "name": "Granite 3.1 8B",
        "family": "granite",
        "params_b": 8.17,
        "architecture": "dense",
        "capabilities": ["chat", "coding"],
        "context_length": 131072,
        "release_date": "2024-12-16",
        "hf_id": "ibm-granite/granite-3.1-8b-instruct",
        "provider": "IBM",
        "hf_downloads": 50000,
        "quantizations": quants(8.17),
        "benchmarks": empty_benchmarks(humaneval=65.0, ifeval=79.0, mmlu_pro=42.0),
        "gguf_sources": [{"repo": "bartowski/granite-3.1-8b-instruct-GGUF", "provider": "bartowski"}],
    },

    # ── Nous/OpenHermes additions ─────────────────────────────────────────────
    {
        "id": "openhermes-2.5-7b",
        "name": "OpenHermes 2.5 7B",
        "family": "other",
        "params_b": 7.25,
        "architecture": "dense",
        "capabilities": ["chat"],
        "context_length": 32768,
        "release_date": "2023-11-01",
        "hf_id": "teknium/OpenHermes-2.5-Mistral-7B",
        "provider": "Teknium",
        "hf_downloads": 800000,
        "ollama_base": "openhermes",
        "quantizations": quants(7.25, "openhermes"),
        "benchmarks": empty_benchmarks(humaneval=48.0),
        "gguf_sources": [{"repo": "TheBloke/OpenHermes-2.5-Mistral-7B-GGUF", "provider": "TheBloke"}],
    },
    {
        "id": "nous-hermes2-34b",
        "name": "Nous Hermes 2 34B",
        "family": "other",
        "params_b": 34.0,
        "architecture": "dense",
        "capabilities": ["chat"],
        "context_length": 8192,
        "release_date": "2024-02-01",
        "hf_id": "NousResearch/Nous-Hermes-2-Yi-34B",
        "provider": "Nous Research",
        "hf_downloads": 100000,
        "quantizations": quants(34.0),
        "benchmarks": empty_benchmarks(humaneval=54.0, mmlu_pro=40.0),
        "gguf_sources": [{"repo": "TheBloke/Nous-Hermes-2-Yi-34B-GGUF", "provider": "TheBloke"}],
    },
    {
        "id": "capybara-34b",
        "name": "Nous Capybara 34B",
        "family": "other",
        "params_b": 34.4,
        "architecture": "dense",
        "capabilities": ["chat"],
        "context_length": 8192,
        "release_date": "2023-12-01",
        "hf_id": "NousResearch/Nous-Capybara-34B",
        "provider": "Nous Research",
        "hf_downloads": 30000,
        "quantizations": quants(34.4),
        "benchmarks": empty_benchmarks(humaneval=42.0),
        "gguf_sources": [{"repo": "TheBloke/Nous-Capybara-34B-GGUF", "provider": "TheBloke"}],
    },

    # ── Nemotron additions (NVIDIA) ───────────────────────────────────────────
    {
        "id": "llama3.1-nemotron-70b",
        "name": "Llama-3.1-Nemotron-70B",
        "family": "nemotron",
        "params_b": 70.6,
        "architecture": "dense",
        "capabilities": ["chat", "reasoning"],
        "context_length": 131072,
        "release_date": "2024-10-03",
        "hf_id": "nvidia/Llama-3.1-Nemotron-70B-Instruct-HF",
        "provider": "NVIDIA",
        "hf_downloads": 200000,
        "quantizations": quants(70.6),
        "benchmarks": empty_benchmarks(humaneval=77.0, mmlu_pro=60.0, math=72.0, ifeval=85.0, bbh=80.0, gpqa=51.9),
        "gguf_sources": [{"repo": "bartowski/Llama-3.1-Nemotron-70B-Instruct-HF-GGUF", "provider": "bartowski"}],
    },
    {
        "id": "nemotron-4-340b",
        "name": "Nemotron-4 340B",
        "family": "nemotron",
        "params_b": 340.0,
        "architecture": "dense",
        "capabilities": ["chat", "reasoning"],
        "context_length": 4096,
        "release_date": "2024-06-14",
        "hf_id": "nvidia/Nemotron-4-340B-Instruct",
        "provider": "NVIDIA",
        "hf_downloads": 10000,
        "quantizations": quants(340.0),
        "benchmarks": empty_benchmarks(humaneval=73.2, mmlu_pro=62.0, math=41.1, ifeval=85.1),
    },

    # ── Zephyr additions ──────────────────────────────────────────────────────
    {
        "id": "zephyr-3b",
        "name": "Zephyr 3B",
        "family": "zephyr",
        "params_b": 2.79,
        "architecture": "dense",
        "capabilities": ["chat"],
        "context_length": 4096,
        "release_date": "2024-01-17",
        "hf_id": "HuggingFaceH4/tiny-random-LlamaForCausalLM",
        "provider": "HuggingFace",
        "hf_downloads": 50000,
        "quantizations": quants(2.79),
        "benchmarks": empty_benchmarks(ifeval=49.0),
        "gguf_sources": [{"repo": "bartowski/stablelm-zephyr-3b-GGUF", "provider": "bartowski"}],
    },

    # ── Solar additions (Upstage) ─────────────────────────────────────────────
    {
        "id": "solar-pro-22b",
        "name": "SOLAR-Pro 22B",
        "family": "solar",
        "params_b": 22.1,
        "architecture": "dense",
        "capabilities": ["chat", "reasoning"],
        "context_length": 4096,
        "release_date": "2024-10-15",
        "hf_id": "upstage/solar-pro-preview-instruct",
        "provider": "Upstage",
        "hf_downloads": 30000,
        "quantizations": quants(22.1),
        "benchmarks": empty_benchmarks(humaneval=66.0, mmlu_pro=48.0, ifeval=73.0, bbh=69.0),
        "gguf_sources": [{"repo": "bartowski/solar-pro-preview-instruct-GGUF", "provider": "bartowski"}],
    },

    # ── Qwen3 family (Alibaba, 2025) ─────────────────────────────────────────
    {
        "id": "qwen3-0.6b",
        "name": "Qwen3 0.6B",
        "family": "qwen",
        "params_b": 0.6,
        "architecture": "dense",
        "capabilities": ["chat", "reasoning"],
        "context_length": 32768,
        "release_date": "2025-04-28",
        "hf_id": "Qwen/Qwen3-0.6B",
        "provider": "Alibaba",
        "hf_downloads": 200000,
        "ollama_base": "qwen3:0.6b",
        "quantizations": quants(0.6, "qwen3:0.6b"),
        "benchmarks": empty_benchmarks(humaneval=62.0, math=65.0, ifeval=60.0),
        "gguf_sources": [{"repo": "bartowski/Qwen3-0.6B-GGUF", "provider": "bartowski"}],
    },
    {
        "id": "qwen3-1.7b",
        "name": "Qwen3 1.7B",
        "family": "qwen",
        "params_b": 1.7,
        "architecture": "dense",
        "capabilities": ["chat", "reasoning"],
        "context_length": 32768,
        "release_date": "2025-04-28",
        "hf_id": "Qwen/Qwen3-1.7B",
        "provider": "Alibaba",
        "hf_downloads": 300000,
        "ollama_base": "qwen3:1.7b",
        "quantizations": quants(1.7, "qwen3:1.7b"),
        "benchmarks": empty_benchmarks(humaneval=68.0, math=72.0, ifeval=65.0),
        "gguf_sources": [{"repo": "bartowski/Qwen3-1.7B-GGUF", "provider": "bartowski"}],
    },
    {
        "id": "qwen3-4b",
        "name": "Qwen3 4B",
        "family": "qwen",
        "params_b": 4.0,
        "architecture": "dense",
        "capabilities": ["chat", "reasoning"],
        "context_length": 32768,
        "release_date": "2025-04-28",
        "hf_id": "Qwen/Qwen3-4B",
        "provider": "Alibaba",
        "hf_downloads": 500000,
        "ollama_base": "qwen3:4b",
        "quantizations": quants(4.0, "qwen3:4b"),
        "benchmarks": empty_benchmarks(humaneval=78.0, math=82.0, ifeval=72.0, mmlu_pro=48.0),
        "gguf_sources": [{"repo": "bartowski/Qwen3-4B-GGUF", "provider": "bartowski"}],
    },
    {
        "id": "qwen3-8b",
        "name": "Qwen3 8B",
        "family": "qwen",
        "params_b": 8.2,
        "architecture": "dense",
        "capabilities": ["chat", "reasoning"],
        "context_length": 32768,
        "release_date": "2025-04-28",
        "hf_id": "Qwen/Qwen3-8B",
        "provider": "Alibaba",
        "hf_downloads": 800000,
        "ollama_base": "qwen3:8b",
        "quantizations": quants(8.2, "qwen3:8b"),
        "benchmarks": empty_benchmarks(humaneval=85.0, math=89.0, ifeval=78.0, mmlu_pro=55.0, gpqa=45.0),
        "gguf_sources": [{"repo": "bartowski/Qwen3-8B-GGUF", "provider": "bartowski"}],
    },
    {
        "id": "qwen3-14b",
        "name": "Qwen3 14B",
        "family": "qwen",
        "params_b": 14.8,
        "architecture": "dense",
        "capabilities": ["chat", "reasoning"],
        "context_length": 32768,
        "release_date": "2025-04-28",
        "hf_id": "Qwen/Qwen3-14B",
        "provider": "Alibaba",
        "hf_downloads": 600000,
        "ollama_base": "qwen3:14b",
        "quantizations": quants(14.8, "qwen3:14b"),
        "benchmarks": empty_benchmarks(humaneval=88.0, math=91.0, ifeval=82.0, mmlu_pro=62.0, gpqa=52.0),
        "gguf_sources": [{"repo": "bartowski/Qwen3-14B-GGUF", "provider": "bartowski"}],
    },
    {
        "id": "qwen3-30b-a3b",
        "name": "Qwen3 30B A3B",
        "family": "qwen",
        "params_b": 30.5,
        "architecture": "moe",
        "capabilities": ["chat", "reasoning"],
        "context_length": 32768,
        "release_date": "2025-04-28",
        "hf_id": "Qwen/Qwen3-30B-A3B",
        "provider": "Alibaba",
        "hf_downloads": 400000,
        "ollama_base": "qwen3:30b-a3b",
        "quantizations": quants(30.5, "qwen3:30b-a3b"),
        "benchmarks": empty_benchmarks(humaneval=86.0, math=90.0, ifeval=80.0, mmlu_pro=58.0, gpqa=48.0),
        "gguf_sources": [{"repo": "bartowski/Qwen3-30B-A3B-GGUF", "provider": "bartowski"}],
    },
    {
        "id": "qwen3-32b",
        "name": "Qwen3 32B",
        "family": "qwen",
        "params_b": 32.8,
        "architecture": "dense",
        "capabilities": ["chat", "reasoning"],
        "context_length": 32768,
        "release_date": "2025-04-28",
        "hf_id": "Qwen/Qwen3-32B",
        "provider": "Alibaba",
        "hf_downloads": 700000,
        "ollama_base": "qwen3:32b",
        "quantizations": quants(32.8, "qwen3:32b"),
        "benchmarks": empty_benchmarks(humaneval=92.0, math=93.0, ifeval=85.0, mmlu_pro=66.0, gpqa=58.0),
        "gguf_sources": [{"repo": "bartowski/Qwen3-32B-GGUF", "provider": "bartowski"}],
    },
    {
        "id": "qwen3-235b-a22b",
        "name": "Qwen3 235B A22B",
        "family": "qwen",
        "params_b": 235.0,
        "architecture": "moe",
        "capabilities": ["chat", "reasoning"],
        "context_length": 32768,
        "release_date": "2025-04-28",
        "hf_id": "Qwen/Qwen3-235B-A22B",
        "provider": "Alibaba",
        "hf_downloads": 100000,
        "quantizations": quants(235.0),
        "benchmarks": empty_benchmarks(humaneval=95.0, math=96.0, ifeval=88.0, mmlu_pro=72.0, gpqa=66.0),
        "gguf_sources": [{"repo": "bartowski/Qwen3-235B-A22B-GGUF", "provider": "bartowski"}],
    },

    # ── DeepSeek additions ────────────────────────────────────────────────────
    {
        "id": "deepseek-v2.5-236b",
        "name": "DeepSeek-V2.5 236B",
        "family": "deepseek",
        "params_b": 236.0,
        "architecture": "moe",
        "capabilities": ["chat", "coding"],
        "context_length": 131072,
        "release_date": "2024-09-05",
        "hf_id": "deepseek-ai/DeepSeek-V2.5",
        "provider": "DeepSeek",
        "hf_downloads": 100000,
        "quantizations": quants(236.0),
        "benchmarks": empty_benchmarks(humaneval=87.6, mmlu_pro=71.0, math=74.7, ifeval=80.0, bbh=82.0),
        "gguf_sources": [{"repo": "bartowski/DeepSeek-V2.5-GGUF", "provider": "bartowski"}],
    },
    {
        "id": "deepseek-vl2-small-16b",
        "name": "DeepSeek-VL2 Small 16B",
        "family": "deepseek",
        "params_b": 15.7,
        "architecture": "moe",
        "capabilities": ["chat", "vision"],
        "context_length": 4096,
        "release_date": "2024-12-13",
        "hf_id": "deepseek-ai/deepseek-vl2-small",
        "provider": "DeepSeek",
        "hf_downloads": 50000,
        "quantizations": quants(15.7),
        "benchmarks": empty_benchmarks(mmbench=73.0, mmmu=49.0),
        "gguf_sources": [{"repo": "bartowski/deepseek-vl2-small-GGUF", "provider": "bartowski"}],
    },
    {
        "id": "janus-pro-7b",
        "name": "Janus-Pro 7B",
        "family": "deepseek",
        "params_b": 7.3,
        "architecture": "dense",
        "capabilities": ["chat", "vision"],
        "context_length": 4096,
        "release_date": "2025-01-27",
        "hf_id": "deepseek-ai/Janus-Pro-7B",
        "provider": "DeepSeek",
        "hf_downloads": 80000,
        "quantizations": quants(7.3),
        "benchmarks": empty_benchmarks(mmbench=67.0, mmmu=41.0),
        "gguf_sources": [{"repo": "bartowski/Janus-Pro-7B-GGUF", "provider": "bartowski"}],
    },

    # ── Phi additions ─────────────────────────────────────────────────────────
    {
        "id": "phi-3.5-mini-3.8b",
        "name": "Phi-3.5 Mini 3.8B",
        "family": "phi",
        "params_b": 3.82,
        "architecture": "dense",
        "capabilities": ["chat", "coding", "reasoning"],
        "context_length": 131072,
        "release_date": "2024-08-20",
        "hf_id": "microsoft/Phi-3.5-mini-instruct",
        "provider": "Microsoft",
        "hf_downloads": 500000,
        "ollama_base": "phi3.5:3.8b",
        "quantizations": quants(3.82, "phi3.5:3.8b"),
        "benchmarks": empty_benchmarks(humaneval=62.0, mmlu_pro=47.4, math=59.0, ifeval=69.0, bbh=62.0, gpqa=30.5),
        "gguf_sources": [{"repo": "bartowski/Phi-3.5-mini-instruct-GGUF", "provider": "bartowski"}],
    },
    {
        "id": "phi-3.5-moe-42b",
        "name": "Phi-3.5 MoE 42B",
        "family": "phi",
        "params_b": 41.9,
        "architecture": "moe",
        "capabilities": ["chat", "coding", "reasoning"],
        "context_length": 131072,
        "release_date": "2024-08-20",
        "hf_id": "microsoft/Phi-3.5-MoE-instruct",
        "provider": "Microsoft",
        "hf_downloads": 200000,
        "quantizations": quants(41.9),
        "benchmarks": empty_benchmarks(humaneval=77.0, mmlu_pro=60.8, math=66.0, ifeval=79.0, bbh=72.0, gpqa=43.0),
        "gguf_sources": [{"repo": "bartowski/Phi-3.5-MoE-instruct-GGUF", "provider": "bartowski"}],
    },

    # ── Llama 4 Maverick ──────────────────────────────────────────────────────
    {
        "id": "llama-4-maverick-400b",
        "name": "Llama-4-Maverick-17B-128E",
        "family": "llama",
        "params_b": 400.0,
        "architecture": "moe",
        "capabilities": ["chat", "vision", "reasoning"],
        "context_length": 1048576,
        "release_date": "2025-04-05",
        "hf_id": "meta-llama/Llama-4-Maverick-17B-128E-Instruct",
        "provider": "Meta",
        "hf_downloads": 50000,
        "quantizations": quants(400.0),
        "benchmarks": empty_benchmarks(humaneval=85.0, mmlu_pro=69.0, math=78.0, ifeval=86.0, mmbench=78.0, mmmu=61.0),
        "gguf_sources": [{"repo": "bartowski/Llama-4-Maverick-17B-128E-Instruct-GGUF", "provider": "bartowski"}],
    },

    # ── Llama 3.2 90B Vision ──────────────────────────────────────────────────
    {
        "id": "llama-vision-90b",
        "name": "Llama-3.2-90B-Vision",
        "family": "llama",
        "params_b": 88.6,
        "architecture": "dense",
        "capabilities": ["chat", "vision"],
        "context_length": 131072,
        "release_date": "2024-09-25",
        "hf_id": "meta-llama/Llama-3.2-90B-Vision-Instruct",
        "provider": "Meta",
        "hf_downloads": 80000,
        "quantizations": quants(88.6),
        "benchmarks": empty_benchmarks(humaneval=72.0, mmlu_pro=55.0, mmbench=76.8, mmmu=60.3),
        "gguf_sources": [{"repo": "bartowski/Llama-3.2-90B-Vision-Instruct-GGUF", "provider": "bartowski"}],
    },

    # ── Llama 3.0 8B (distinct from 3.1) ─────────────────────────────────────
    {
        "id": "llama3-8b",
        "name": "Llama 3 8B",
        "family": "llama",
        "params_b": 8.0,
        "architecture": "dense",
        "capabilities": ["chat"],
        "context_length": 8192,
        "release_date": "2024-04-18",
        "hf_id": "meta-llama/Meta-Llama-3-8B-Instruct",
        "provider": "Meta",
        "hf_downloads": 3000000,
        "ollama_base": "llama3:8b",
        "quantizations": quants(8.0, "llama3:8b"),
        "benchmarks": empty_benchmarks(humaneval=62.2, mmlu_pro=35.0, math=30.0, ifeval=68.4, bbh=61.1),
        "gguf_sources": [{"repo": "bartowski/Meta-Llama-3-8B-Instruct-GGUF", "provider": "bartowski"}],
    },
    {
        "id": "llama3-70b",
        "name": "Llama 3 70B",
        "family": "llama",
        "params_b": 70.6,
        "architecture": "dense",
        "capabilities": ["chat", "coding"],
        "context_length": 8192,
        "release_date": "2024-04-18",
        "hf_id": "meta-llama/Meta-Llama-3-70B-Instruct",
        "provider": "Meta",
        "hf_downloads": 2000000,
        "ollama_base": "llama3:70b",
        "quantizations": quants(70.6, "llama3:70b"),
        "benchmarks": empty_benchmarks(humaneval=72.0, mmlu_pro=55.0, math=50.4, ifeval=77.6, bbh=81.0, gpqa=39.5),
        "gguf_sources": [{"repo": "bartowski/Meta-Llama-3-70B-Instruct-GGUF", "provider": "bartowski"}],
    },

    # ── Llama 1 original ─────────────────────────────────────────────────────
    {
        "id": "llama1-7b",
        "name": "LLaMA 1 7B",
        "family": "llama",
        "params_b": 7.0,
        "architecture": "dense",
        "capabilities": ["chat"],
        "context_length": 2048,
        "release_date": "2023-02-24",
        "hf_id": "huggyllama/llama-7b",
        "provider": "Meta",
        "hf_downloads": 300000,
        "quantizations": quants(7.0),
        "benchmarks": empty_benchmarks(humaneval=10.5),
        "gguf_sources": [{"repo": "TheBloke/LLaMA-7b-GGUF", "provider": "TheBloke"}],
    },
    {
        "id": "llama1-13b",
        "name": "LLaMA 1 13B",
        "family": "llama",
        "params_b": 13.0,
        "architecture": "dense",
        "capabilities": ["chat"],
        "context_length": 2048,
        "release_date": "2023-02-24",
        "hf_id": "huggyllama/llama-13b",
        "provider": "Meta",
        "hf_downloads": 200000,
        "quantizations": quants(13.0),
        "benchmarks": empty_benchmarks(humaneval=15.8),
        "gguf_sources": [{"repo": "TheBloke/LLaMA-13b-GGUF", "provider": "TheBloke"}],
    },
    {
        "id": "llama1-30b",
        "name": "LLaMA 1 30B",
        "family": "llama",
        "params_b": 33.0,
        "architecture": "dense",
        "capabilities": ["chat"],
        "context_length": 2048,
        "release_date": "2023-02-24",
        "hf_id": "huggyllama/llama-30b",
        "provider": "Meta",
        "hf_downloads": 100000,
        "quantizations": quants(33.0),
        "benchmarks": empty_benchmarks(humaneval=21.4),
        "gguf_sources": [{"repo": "TheBloke/LLaMA-30B-GGUF", "provider": "TheBloke"}],
    },
    {
        "id": "llama1-65b",
        "name": "LLaMA 1 65B",
        "family": "llama",
        "params_b": 65.2,
        "architecture": "dense",
        "capabilities": ["chat"],
        "context_length": 2048,
        "release_date": "2023-02-24",
        "hf_id": "huggyllama/llama-65b",
        "provider": "Meta",
        "hf_downloads": 80000,
        "quantizations": quants(65.2),
        "benchmarks": empty_benchmarks(humaneval=23.7),
        "gguf_sources": [{"repo": "TheBloke/LLaMA-65B-GGUF", "provider": "TheBloke"}],
    },

    # ── Mistral-Nemo 12B ──────────────────────────────────────────────────────
    # (already have mistral-nemo-12.2b but let's add Mistral-7B-v0.1 for historical completeness)
    {
        "id": "mistral-7b-v0.1",
        "name": "Mistral 7B v0.1",
        "family": "mistral",
        "params_b": 7.25,
        "architecture": "dense",
        "capabilities": ["chat"],
        "context_length": 32768,
        "release_date": "2023-09-27",
        "hf_id": "mistralai/Mistral-7B-Instruct-v0.1",
        "provider": "Mistral AI",
        "hf_downloads": 2000000,
        "quantizations": quants(7.25),
        "benchmarks": empty_benchmarks(humaneval=43.9),
        "gguf_sources": [{"repo": "TheBloke/Mistral-7B-Instruct-v0.1-GGUF", "provider": "TheBloke"}],
    },

    # ── Mixtral 8x22B ─────────────────────────────────────────────────────────
    # (already have mistral-140.6b but let's confirm; if that's 8x22B, skip. Add 8x22B-Instruct separately)
    # mistral-140.6b seems like Mixtral 8x22B at 141B. Let's add a WizardLM fine-tune of it.

    # ── Phind CodeLlama ───────────────────────────────────────────────────────
    {
        "id": "phind-codellama-34b",
        "name": "Phind CodeLlama 34B",
        "family": "other",
        "params_b": 34.0,
        "architecture": "dense",
        "capabilities": ["coding"],
        "context_length": 16384,
        "release_date": "2023-08-27",
        "hf_id": "Phind/Phind-CodeLlama-34B-v2",
        "provider": "Phind",
        "hf_downloads": 100000,
        "quantizations": quants(34.0),
        "benchmarks": empty_benchmarks(humaneval=73.8, mbpp=62.3),
        "gguf_sources": [{"repo": "TheBloke/Phind-CodeLlama-34B-v2-GGUF", "provider": "TheBloke"}],
    },

    # ── DeepCoder (Agentica) ──────────────────────────────────────────────────
    {
        "id": "deepcoder-14b",
        "name": "DeepCoder 14B",
        "family": "other",
        "params_b": 14.8,
        "architecture": "dense",
        "capabilities": ["coding", "reasoning"],
        "context_length": 131072,
        "release_date": "2025-04-16",
        "hf_id": "agentica-org/DeepCoder-14B-Preview",
        "provider": "Agentica",
        "hf_downloads": 30000,
        "quantizations": quants(14.8),
        "benchmarks": empty_benchmarks(humaneval=82.0, mbpp=75.0),
        "gguf_sources": [{"repo": "bartowski/DeepCoder-14B-Preview-GGUF", "provider": "bartowski"}],
    },

    # ── Ministral (Mistral, 2024) ─────────────────────────────────────────────
    {
        "id": "ministral-8b",
        "name": "Ministral 8B",
        "family": "mistral",
        "params_b": 8.0,
        "architecture": "dense",
        "capabilities": ["chat"],
        "context_length": 131072,
        "release_date": "2024-10-16",
        "hf_id": "mistralai/Ministral-8B-Instruct-2410",
        "provider": "Mistral AI",
        "hf_downloads": 100000,
        "quantizations": quants(8.0),
        "benchmarks": empty_benchmarks(humaneval=62.0, mmlu_pro=42.0, ifeval=68.0, bbh=60.0),
        "gguf_sources": [{"repo": "bartowski/Ministral-8B-Instruct-2410-GGUF", "provider": "bartowski"}],
    },
    {
        "id": "ministral-3b",
        "name": "Ministral 3B",
        "family": "mistral",
        "params_b": 3.0,
        "architecture": "dense",
        "capabilities": ["chat"],
        "context_length": 131072,
        "release_date": "2024-10-16",
        "hf_id": "mistralai/Ministral-3B-Instruct-2410",
        "provider": "Mistral AI",
        "hf_downloads": 80000,
        "quantizations": quants(3.0),
        "benchmarks": empty_benchmarks(humaneval=44.0, mmlu_pro=29.0, ifeval=54.0),
        "gguf_sources": [{"repo": "bartowski/Ministral-3B-Instruct-2410-GGUF", "provider": "bartowski"}],
    },

    # ── Mistral-Small 3 ───────────────────────────────────────────────────────
    {
        "id": "mistral-small-22b-2409",
        "name": "Mistral Small 22B",
        "family": "mistral",
        "params_b": 22.2,
        "architecture": "dense",
        "capabilities": ["chat", "coding"],
        "context_length": 32768,
        "release_date": "2024-09-18",
        "hf_id": "mistralai/Mistral-Small-Instruct-2409",
        "provider": "Mistral AI",
        "hf_downloads": 120000,
        "quantizations": quants(22.2),
        "benchmarks": empty_benchmarks(humaneval=68.0, mmlu_pro=48.0, ifeval=72.0, bbh=64.0),
        "gguf_sources": [{"repo": "bartowski/Mistral-Small-Instruct-2409-GGUF", "provider": "bartowski"}],
    },

    # ── Gemma 2 2B ────────────────────────────────────────────────────────────
    {
        "id": "gemma2-2.6b",
        "name": "Gemma 2 2B",
        "family": "gemma",
        "params_b": 2.61,
        "architecture": "dense",
        "capabilities": ["chat"],
        "context_length": 8192,
        "release_date": "2024-07-31",
        "hf_id": "google/gemma-2-2b-it",
        "provider": "Google",
        "hf_downloads": 600000,
        "ollama_base": "gemma2:2b",
        "quantizations": quants(2.61, "gemma2:2b"),
        "benchmarks": empty_benchmarks(humaneval=52.3, mmlu_pro=28.0, ifeval=59.0, bbh=60.0),
        "gguf_sources": [{"repo": "bartowski/gemma-2-2b-it-GGUF", "provider": "bartowski"}],
    },

    # ── CodeGemma ─────────────────────────────────────────────────────────────
    {
        "id": "codegemma-7b",
        "name": "CodeGemma 7B",
        "family": "gemma",
        "params_b": 8.54,
        "architecture": "dense",
        "capabilities": ["coding"],
        "context_length": 8192,
        "release_date": "2024-04-09",
        "hf_id": "google/codegemma-7b-it",
        "provider": "Google",
        "hf_downloads": 200000,
        "ollama_base": "codegemma:7b",
        "quantizations": quants(8.54, "codegemma:7b"),
        "benchmarks": empty_benchmarks(humaneval=56.1, mbpp=55.0),
        "gguf_sources": [{"repo": "bartowski/codegemma-7b-it-GGUF", "provider": "bartowski"}],
    },
    {
        "id": "codegemma-2b",
        "name": "CodeGemma 2B",
        "family": "gemma",
        "params_b": 2.51,
        "architecture": "dense",
        "capabilities": ["coding"],
        "context_length": 8192,
        "release_date": "2024-04-09",
        "hf_id": "google/codegemma-2b",
        "provider": "Google",
        "hf_downloads": 100000,
        "quantizations": quants(2.51),
        "benchmarks": empty_benchmarks(humaneval=27.2, mbpp=27.9),
        "gguf_sources": [{"repo": "bartowski/codegemma-2b-GGUF", "provider": "bartowski"}],
    },

    # ── Qwen2-VL ─────────────────────────────────────────────────────────────
    {
        "id": "qwen2-vl-7b",
        "name": "Qwen2-VL 7B",
        "family": "qwen",
        "params_b": 8.29,
        "architecture": "dense",
        "capabilities": ["chat", "vision"],
        "context_length": 32768,
        "release_date": "2024-10-03",
        "hf_id": "Qwen/Qwen2-VL-7B-Instruct",
        "provider": "Alibaba",
        "hf_downloads": 400000,
        "ollama_base": "qwen2-vl:7b",
        "quantizations": quants(8.29, "qwen2-vl:7b"),
        "benchmarks": empty_benchmarks(mmbench=81.8, mmmu=54.1, humaneval=60.0),
        "gguf_sources": [{"repo": "bartowski/Qwen2-VL-7B-Instruct-GGUF", "provider": "bartowski"}],
    },
    {
        "id": "qwen2-vl-72b",
        "name": "Qwen2-VL 72B",
        "family": "qwen",
        "params_b": 72.7,
        "architecture": "dense",
        "capabilities": ["chat", "vision"],
        "context_length": 32768,
        "release_date": "2024-10-03",
        "hf_id": "Qwen/Qwen2-VL-72B-Instruct",
        "provider": "Alibaba",
        "hf_downloads": 200000,
        "quantizations": quants(72.7),
        "benchmarks": empty_benchmarks(mmbench=86.9, mmmu=64.5, humaneval=76.0),
        "gguf_sources": [{"repo": "bartowski/Qwen2-VL-72B-Instruct-GGUF", "provider": "bartowski"}],
    },
    {
        "id": "qwen2-vl-2b",
        "name": "Qwen2-VL 2B",
        "family": "qwen",
        "params_b": 2.21,
        "architecture": "dense",
        "capabilities": ["chat", "vision"],
        "context_length": 32768,
        "release_date": "2024-10-03",
        "hf_id": "Qwen/Qwen2-VL-2B-Instruct",
        "provider": "Alibaba",
        "hf_downloads": 300000,
        "quantizations": quants(2.21),
        "benchmarks": empty_benchmarks(mmbench=74.7, mmmu=41.1),
        "gguf_sources": [{"repo": "bartowski/Qwen2-VL-2B-Instruct-GGUF", "provider": "bartowski"}],
    },

    # ── Llama 3.1 405B ────────────────────────────────────────────────────────
    {
        "id": "llama-3.1-405b",
        "name": "Llama 3.1 405B",
        "family": "llama",
        "params_b": 405.0,
        "architecture": "dense",
        "capabilities": ["chat", "coding", "reasoning"],
        "context_length": 131072,
        "release_date": "2024-07-23",
        "hf_id": "meta-llama/Llama-3.1-405B-Instruct",
        "provider": "Meta",
        "hf_downloads": 100000,
        "quantizations": quants(405.0),
        "benchmarks": empty_benchmarks(humaneval=89.0, mmlu_pro=73.3, math=73.8, ifeval=88.6, bbh=88.5, gpqa=51.1),
        "gguf_sources": [{"repo": "bartowski/Meta-Llama-3.1-405B-Instruct-GGUF", "provider": "bartowski"}],
    },

    # ── StarCoder (older) ─────────────────────────────────────────────────────
    {
        "id": "starcoder-15b",
        "name": "StarCoder 15B",
        "family": "starcoder",
        "params_b": 15.5,
        "architecture": "dense",
        "capabilities": ["coding"],
        "context_length": 8192,
        "release_date": "2023-05-09",
        "hf_id": "bigcode/starchat-beta",
        "provider": "BigCode",
        "hf_downloads": 300000,
        "quantizations": quants(15.5),
        "benchmarks": empty_benchmarks(humaneval=33.6, mbpp=43.0),
        "gguf_sources": [{"repo": "TheBloke/starchat-beta-GGUF", "provider": "TheBloke"}],
    },

    # ── Gemma 1 CodeGemma (fill-in-middle) ───────────────────────────────────
    # Already covered with starcoder family above

    # ── Mistral Large 2 ──────────────────────────────────────────────────────
    {
        "id": "mistral-large-2-123b",
        "name": "Mistral Large 2 123B",
        "family": "mistral",
        "params_b": 123.0,
        "architecture": "dense",
        "capabilities": ["chat", "coding", "reasoning"],
        "context_length": 131072,
        "release_date": "2024-07-24",
        "hf_id": "mistralai/Mistral-Large-Instruct-2407",
        "provider": "Mistral AI",
        "hf_downloads": 60000,
        "quantizations": quants(123.0),
        "benchmarks": empty_benchmarks(humaneval=92.0, mmlu_pro=69.0, math=69.0, ifeval=88.0, bbh=81.0, gpqa=49.0),
        "gguf_sources": [{"repo": "bartowski/Mistral-Large-Instruct-2407-GGUF", "provider": "bartowski"}],
    },
]


# ─────────────────────────────────────────────────────────────────────────────
# MERGE & SAVE
# ─────────────────────────────────────────────────────────────────────────────
with open("public/data/models.json") as f:
    existing = json.load(f)

existing_ids = {m["id"] for m in existing}
added = 0
for m in NEW_MODELS:
    if m["id"] not in existing_ids:
        existing.append(m)
        added += 1
    else:
        print(f"  SKIP (duplicate): {m['id']}")

# Sort by family then params_b
existing.sort(key=lambda m: (m["family"], m["params_b"]))

with open("public/data/models.json", "w") as f:
    json.dump(existing, f, indent=2)

print(f"\nDone! Added {added} new models.")
print(f"Total models: {len(existing)}")

# Summary by family
families = {}
for m in existing:
    fam = m.get("family", "unknown")
    families[fam] = families.get(fam, 0) + 1
for fam, count in sorted(families.items(), key=lambda x: -x[1]):
    print(f"  {fam}: {count}")
