#!/usr/bin/env python3
"""
Expand public/data/gpus.json with comprehensive GPU data.
Adds data-center, older consumer, AMD RDNA4/Instinct, more Apple Silicon.
"""
import json

NEW_GPUS = [

    # ── NVIDIA Data Center / Professional ────────────────────────────────────

    {
        "name": "NVIDIA H200 SXM 141GB",
        "vendor": "nvidia",
        "vram_mb": 143360,          # 141 GB
        "bandwidth_gbps": 4800,
        "memory_type": "HBM3e",
        "cuda_cores": 16896,
        "tensor_cores": 528,
        "fp32_tflops": 67.0,
        "fp16_tflops": 1979.0,
        "architecture": "Hopper",
        "compute_capability": "9.0",
        "tdp_watts": 700,
        "pcie_gen": 5,
        "pcie_lanes": 16,
        "aliases": ["H200", "H200 SXM", "NVIDIA H200"],
        "availability": "available",
        "price_usd": 40000,
    },
    {
        "name": "NVIDIA H100 SXM5 80GB",
        "vendor": "nvidia",
        "vram_mb": 81920,
        "bandwidth_gbps": 3350,
        "memory_type": "HBM3",
        "cuda_cores": 16896,
        "tensor_cores": 528,
        "fp32_tflops": 67.0,
        "fp16_tflops": 1979.0,
        "architecture": "Hopper",
        "compute_capability": "9.0",
        "tdp_watts": 700,
        "pcie_gen": 5,
        "pcie_lanes": 16,
        "aliases": ["H100 SXM", "H100", "NVIDIA H100 SXM", "H100 SXM5"],
        "availability": "available",
        "price_usd": 30000,
    },
    {
        "name": "NVIDIA H100 PCIe 80GB",
        "vendor": "nvidia",
        "vram_mb": 81920,
        "bandwidth_gbps": 2000,
        "memory_type": "HBM2e",
        "cuda_cores": 14592,
        "tensor_cores": 456,
        "fp32_tflops": 51.0,
        "fp16_tflops": 1513.0,
        "architecture": "Hopper",
        "compute_capability": "9.0",
        "tdp_watts": 350,
        "pcie_gen": 5,
        "pcie_lanes": 16,
        "aliases": ["H100 PCIe", "NVIDIA H100 PCIe"],
        "availability": "available",
        "price_usd": 25000,
    },
    {
        "name": "NVIDIA A100 SXM 80GB",
        "vendor": "nvidia",
        "vram_mb": 81920,
        "bandwidth_gbps": 2000,
        "memory_type": "HBM2e",
        "cuda_cores": 6912,
        "tensor_cores": 432,
        "fp32_tflops": 19.5,
        "fp16_tflops": 312.0,
        "architecture": "Ampere",
        "compute_capability": "8.0",
        "tdp_watts": 400,
        "pcie_gen": 4,
        "pcie_lanes": 16,
        "aliases": ["A100 80GB", "A100 SXM", "NVIDIA A100 80GB", "A100"],
        "availability": "available",
        "price_usd": 15000,
    },
    {
        "name": "NVIDIA A100 PCIe 80GB",
        "vendor": "nvidia",
        "vram_mb": 81920,
        "bandwidth_gbps": 1935,
        "memory_type": "HBM2e",
        "cuda_cores": 6912,
        "tensor_cores": 432,
        "fp32_tflops": 19.5,
        "fp16_tflops": 312.0,
        "architecture": "Ampere",
        "compute_capability": "8.0",
        "tdp_watts": 300,
        "pcie_gen": 4,
        "pcie_lanes": 16,
        "aliases": ["A100 PCIe 80GB", "NVIDIA A100 PCIe"],
        "availability": "available",
        "price_usd": 12000,
    },
    {
        "name": "NVIDIA A100 PCIe 40GB",
        "vendor": "nvidia",
        "vram_mb": 40960,
        "bandwidth_gbps": 1555,
        "memory_type": "HBM2",
        "cuda_cores": 6912,
        "tensor_cores": 432,
        "fp32_tflops": 19.5,
        "fp16_tflops": 312.0,
        "architecture": "Ampere",
        "compute_capability": "8.0",
        "tdp_watts": 300,
        "pcie_gen": 4,
        "pcie_lanes": 16,
        "aliases": ["A100 40GB", "NVIDIA A100 40GB"],
        "availability": "available",
        "price_usd": 8000,
    },
    {
        "name": "NVIDIA L40S 48GB",
        "vendor": "nvidia",
        "vram_mb": 49152,
        "bandwidth_gbps": 864,
        "memory_type": "GDDR6",
        "cuda_cores": 18176,
        "tensor_cores": 568,
        "fp32_tflops": 91.6,
        "fp16_tflops": 183.0,
        "architecture": "Ada Lovelace",
        "compute_capability": "8.9",
        "tdp_watts": 350,
        "pcie_gen": 4,
        "pcie_lanes": 16,
        "aliases": ["L40S", "NVIDIA L40S"],
        "availability": "available",
        "price_usd": 10000,
    },
    {
        "name": "NVIDIA L40 48GB",
        "vendor": "nvidia",
        "vram_mb": 49152,
        "bandwidth_gbps": 864,
        "memory_type": "GDDR6",
        "cuda_cores": 18176,
        "tensor_cores": 568,
        "fp32_tflops": 90.5,
        "fp16_tflops": 181.0,
        "architecture": "Ada Lovelace",
        "compute_capability": "8.9",
        "tdp_watts": 300,
        "pcie_gen": 4,
        "pcie_lanes": 16,
        "aliases": ["L40", "NVIDIA L40"],
        "availability": "available",
        "price_usd": 7000,
    },
    {
        "name": "NVIDIA RTX 6000 Ada 48GB",
        "vendor": "nvidia",
        "vram_mb": 49152,
        "bandwidth_gbps": 960,
        "memory_type": "GDDR6",
        "cuda_cores": 18176,
        "tensor_cores": 568,
        "fp32_tflops": 91.1,
        "fp16_tflops": 182.0,
        "architecture": "Ada Lovelace",
        "compute_capability": "8.9",
        "tdp_watts": 300,
        "pcie_gen": 4,
        "pcie_lanes": 16,
        "aliases": ["RTX 6000 Ada", "NVIDIA RTX 6000 Ada", "RTX6000Ada"],
        "availability": "available",
        "price_usd": 7000,
    },
    {
        "name": "NVIDIA L4 24GB",
        "vendor": "nvidia",
        "vram_mb": 24576,
        "bandwidth_gbps": 300,
        "memory_type": "GDDR6",
        "cuda_cores": 7680,
        "tensor_cores": 240,
        "fp32_tflops": 30.3,
        "fp16_tflops": 121.0,
        "architecture": "Ada Lovelace",
        "compute_capability": "8.9",
        "tdp_watts": 72,
        "pcie_gen": 4,
        "pcie_lanes": 16,
        "aliases": ["L4", "NVIDIA L4"],
        "availability": "available",
        "price_usd": 2500,
    },
    {
        "name": "NVIDIA A40 48GB",
        "vendor": "nvidia",
        "vram_mb": 49152,
        "bandwidth_gbps": 696,
        "memory_type": "GDDR6",
        "cuda_cores": 10752,
        "tensor_cores": 336,
        "fp32_tflops": 37.4,
        "fp16_tflops": 149.7,
        "architecture": "Ampere",
        "compute_capability": "8.6",
        "tdp_watts": 300,
        "pcie_gen": 4,
        "pcie_lanes": 16,
        "aliases": ["A40", "NVIDIA A40"],
        "availability": "available",
        "price_usd": 5000,
    },
    {
        "name": "NVIDIA RTX A6000 48GB",
        "vendor": "nvidia",
        "vram_mb": 49152,
        "bandwidth_gbps": 768,
        "memory_type": "GDDR6",
        "cuda_cores": 10752,
        "tensor_cores": 336,
        "fp32_tflops": 38.7,
        "fp16_tflops": 309.7,
        "architecture": "Ampere",
        "compute_capability": "8.6",
        "tdp_watts": 300,
        "pcie_gen": 4,
        "pcie_lanes": 16,
        "aliases": ["RTX A6000", "NVIDIA RTX A6000", "A6000"],
        "availability": "available",
        "price_usd": 4500,
    },
    {
        "name": "NVIDIA A10 24GB",
        "vendor": "nvidia",
        "vram_mb": 24576,
        "bandwidth_gbps": 600,
        "memory_type": "GDDR6",
        "cuda_cores": 9216,
        "tensor_cores": 288,
        "fp32_tflops": 31.2,
        "fp16_tflops": 125.0,
        "architecture": "Ampere",
        "compute_capability": "8.6",
        "tdp_watts": 150,
        "pcie_gen": 4,
        "pcie_lanes": 16,
        "aliases": ["A10", "NVIDIA A10"],
        "availability": "available",
        "price_usd": 3000,
    },
    {
        "name": "NVIDIA Tesla T4 16GB",
        "vendor": "nvidia",
        "vram_mb": 16384,
        "bandwidth_gbps": 320,
        "memory_type": "GDDR6",
        "cuda_cores": 2560,
        "tensor_cores": 320,
        "fp32_tflops": 8.1,
        "fp16_tflops": 65.1,
        "architecture": "Turing",
        "compute_capability": "7.5",
        "tdp_watts": 70,
        "pcie_gen": 3,
        "pcie_lanes": 16,
        "aliases": ["T4", "Tesla T4", "NVIDIA T4"],
        "availability": "available",
        "price_usd": 2500,
    },
    {
        "name": "NVIDIA V100 SXM2 32GB",
        "vendor": "nvidia",
        "vram_mb": 32768,
        "bandwidth_gbps": 900,
        "memory_type": "HBM2",
        "cuda_cores": 5120,
        "tensor_cores": 640,
        "fp32_tflops": 15.7,
        "fp16_tflops": 125.3,
        "architecture": "Volta",
        "compute_capability": "7.0",
        "tdp_watts": 300,
        "pcie_gen": 3,
        "pcie_lanes": 16,
        "aliases": ["V100 32GB", "V100 SXM", "NVIDIA V100"],
        "availability": "discontinued",
        "price_usd": 3500,
    },
    {
        "name": "NVIDIA V100 PCIe 16GB",
        "vendor": "nvidia",
        "vram_mb": 16384,
        "bandwidth_gbps": 900,
        "memory_type": "HBM2",
        "cuda_cores": 5120,
        "tensor_cores": 640,
        "fp32_tflops": 14.1,
        "fp16_tflops": 112.0,
        "architecture": "Volta",
        "compute_capability": "7.0",
        "tdp_watts": 250,
        "pcie_gen": 3,
        "pcie_lanes": 16,
        "aliases": ["V100 16GB", "NVIDIA V100 PCIe"],
        "availability": "discontinued",
        "price_usd": 2000,
    },
    {
        "name": "NVIDIA RTX 4000 Ada 20GB",
        "vendor": "nvidia",
        "vram_mb": 20480,
        "bandwidth_gbps": 432,
        "memory_type": "GDDR6",
        "cuda_cores": 6144,
        "tensor_cores": 192,
        "fp32_tflops": 26.7,
        "fp16_tflops": 212.0,
        "architecture": "Ada Lovelace",
        "compute_capability": "8.9",
        "tdp_watts": 130,
        "pcie_gen": 4,
        "pcie_lanes": 16,
        "aliases": ["RTX 4000 Ada", "NVIDIA RTX 4000 Ada"],
        "availability": "available",
        "price_usd": 1250,
    },

    # ── NVIDIA RTX 20xx (Turing) ──────────────────────────────────────────────

    {
        "name": "NVIDIA RTX 2080 Ti",
        "vendor": "nvidia",
        "vram_mb": 11264,
        "bandwidth_gbps": 616,
        "memory_type": "GDDR6",
        "cuda_cores": 4352,
        "tensor_cores": 544,
        "fp32_tflops": 13.4,
        "fp16_tflops": 53.8,
        "architecture": "Turing",
        "compute_capability": "7.5",
        "tdp_watts": 250,
        "pcie_gen": 3,
        "pcie_lanes": 16,
        "aliases": ["RTX 2080 Ti", "RTX2080Ti", "NVIDIA RTX 2080 Ti"],
        "availability": "discontinued",
        "price_usd": 350,
    },
    {
        "name": "NVIDIA RTX 2080 SUPER",
        "vendor": "nvidia",
        "vram_mb": 8192,
        "bandwidth_gbps": 496,
        "memory_type": "GDDR6",
        "cuda_cores": 3072,
        "tensor_cores": 384,
        "fp32_tflops": 11.2,
        "fp16_tflops": 22.4,
        "architecture": "Turing",
        "compute_capability": "7.5",
        "tdp_watts": 250,
        "pcie_gen": 3,
        "pcie_lanes": 16,
        "aliases": ["RTX 2080 SUPER", "RTX2080SUPER", "NVIDIA RTX 2080 SUPER"],
        "availability": "discontinued",
        "price_usd": 280,
    },
    {
        "name": "NVIDIA RTX 2080",
        "vendor": "nvidia",
        "vram_mb": 8192,
        "bandwidth_gbps": 448,
        "memory_type": "GDDR6",
        "cuda_cores": 2944,
        "tensor_cores": 368,
        "fp32_tflops": 10.0,
        "fp16_tflops": 20.1,
        "architecture": "Turing",
        "compute_capability": "7.5",
        "tdp_watts": 215,
        "pcie_gen": 3,
        "pcie_lanes": 16,
        "aliases": ["RTX 2080", "RTX2080", "NVIDIA RTX 2080"],
        "availability": "discontinued",
        "price_usd": 260,
    },
    {
        "name": "NVIDIA RTX 2070 SUPER",
        "vendor": "nvidia",
        "vram_mb": 8192,
        "bandwidth_gbps": 448,
        "memory_type": "GDDR6",
        "cuda_cores": 2560,
        "tensor_cores": 320,
        "fp32_tflops": 9.1,
        "fp16_tflops": 18.3,
        "architecture": "Turing",
        "compute_capability": "7.5",
        "tdp_watts": 215,
        "pcie_gen": 3,
        "pcie_lanes": 16,
        "aliases": ["RTX 2070 SUPER", "RTX2070SUPER", "NVIDIA RTX 2070 SUPER"],
        "availability": "discontinued",
        "price_usd": 240,
    },
    {
        "name": "NVIDIA RTX 2070",
        "vendor": "nvidia",
        "vram_mb": 8192,
        "bandwidth_gbps": 448,
        "memory_type": "GDDR6",
        "cuda_cores": 2304,
        "tensor_cores": 288,
        "fp32_tflops": 7.5,
        "fp16_tflops": 14.9,
        "architecture": "Turing",
        "compute_capability": "7.5",
        "tdp_watts": 175,
        "pcie_gen": 3,
        "pcie_lanes": 16,
        "aliases": ["RTX 2070", "RTX2070", "NVIDIA RTX 2070"],
        "availability": "discontinued",
        "price_usd": 200,
    },
    {
        "name": "NVIDIA RTX 2060 SUPER",
        "vendor": "nvidia",
        "vram_mb": 8192,
        "bandwidth_gbps": 448,
        "memory_type": "GDDR6",
        "cuda_cores": 2176,
        "tensor_cores": 272,
        "fp32_tflops": 7.2,
        "fp16_tflops": 14.4,
        "architecture": "Turing",
        "compute_capability": "7.5",
        "tdp_watts": 175,
        "pcie_gen": 3,
        "pcie_lanes": 16,
        "aliases": ["RTX 2060 SUPER", "RTX2060SUPER", "NVIDIA RTX 2060 SUPER"],
        "availability": "discontinued",
        "price_usd": 180,
    },
    {
        "name": "NVIDIA RTX 2060 6GB",
        "vendor": "nvidia",
        "vram_mb": 6144,
        "bandwidth_gbps": 336,
        "memory_type": "GDDR6",
        "cuda_cores": 1920,
        "tensor_cores": 240,
        "fp32_tflops": 6.5,
        "fp16_tflops": 13.0,
        "architecture": "Turing",
        "compute_capability": "7.5",
        "tdp_watts": 160,
        "pcie_gen": 3,
        "pcie_lanes": 16,
        "aliases": ["RTX 2060", "RTX2060", "NVIDIA RTX 2060"],
        "availability": "discontinued",
        "price_usd": 150,
    },

    # ── NVIDIA GTX 16xx (Turing, no RT/Tensor cores for FP16 inference) ──────

    {
        "name": "NVIDIA GTX 1660 SUPER",
        "vendor": "nvidia",
        "vram_mb": 6144,
        "bandwidth_gbps": 336,
        "memory_type": "GDDR6",
        "cuda_cores": 1408,
        "tensor_cores": 0,
        "fp32_tflops": 5.0,
        "fp16_tflops": 5.0,
        "architecture": "Turing",
        "compute_capability": "7.5",
        "tdp_watts": 125,
        "pcie_gen": 3,
        "pcie_lanes": 16,
        "aliases": ["GTX 1660 SUPER", "GTX1660SUPER", "NVIDIA GTX 1660 SUPER"],
        "availability": "discontinued",
        "price_usd": 150,
    },
    {
        "name": "NVIDIA GTX 1660 Ti",
        "vendor": "nvidia",
        "vram_mb": 6144,
        "bandwidth_gbps": 288,
        "memory_type": "GDDR6",
        "cuda_cores": 1536,
        "tensor_cores": 0,
        "fp32_tflops": 5.4,
        "fp16_tflops": 5.4,
        "architecture": "Turing",
        "compute_capability": "7.5",
        "tdp_watts": 120,
        "pcie_gen": 3,
        "pcie_lanes": 16,
        "aliases": ["GTX 1660 Ti", "GTX1660Ti", "NVIDIA GTX 1660 Ti"],
        "availability": "discontinued",
        "price_usd": 140,
    },

    # ── NVIDIA GTX 10xx (Pascal) ──────────────────────────────────────────────

    {
        "name": "NVIDIA GTX 1080 Ti",
        "vendor": "nvidia",
        "vram_mb": 11264,
        "bandwidth_gbps": 484,
        "memory_type": "GDDR5X",
        "cuda_cores": 3584,
        "tensor_cores": 0,
        "fp32_tflops": 11.3,
        "fp16_tflops": 11.3,
        "architecture": "Pascal",
        "compute_capability": "6.1",
        "tdp_watts": 250,
        "pcie_gen": 3,
        "pcie_lanes": 16,
        "aliases": ["GTX 1080 Ti", "GTX1080Ti", "NVIDIA GTX 1080 Ti"],
        "availability": "discontinued",
        "price_usd": 200,
    },
    {
        "name": "NVIDIA GTX 1080",
        "vendor": "nvidia",
        "vram_mb": 8192,
        "bandwidth_gbps": 320,
        "memory_type": "GDDR5X",
        "cuda_cores": 2560,
        "tensor_cores": 0,
        "fp32_tflops": 8.9,
        "fp16_tflops": 8.9,
        "architecture": "Pascal",
        "compute_capability": "6.1",
        "tdp_watts": 180,
        "pcie_gen": 3,
        "pcie_lanes": 16,
        "aliases": ["GTX 1080", "GTX1080", "NVIDIA GTX 1080"],
        "availability": "discontinued",
        "price_usd": 130,
    },
    {
        "name": "NVIDIA GTX 1070 Ti",
        "vendor": "nvidia",
        "vram_mb": 8192,
        "bandwidth_gbps": 256,
        "memory_type": "GDDR5",
        "cuda_cores": 2432,
        "tensor_cores": 0,
        "fp32_tflops": 8.1,
        "fp16_tflops": 8.1,
        "architecture": "Pascal",
        "compute_capability": "6.1",
        "tdp_watts": 180,
        "pcie_gen": 3,
        "pcie_lanes": 16,
        "aliases": ["GTX 1070 Ti", "GTX1070Ti", "NVIDIA GTX 1070 Ti"],
        "availability": "discontinued",
        "price_usd": 120,
    },
    {
        "name": "NVIDIA GTX 1070",
        "vendor": "nvidia",
        "vram_mb": 8192,
        "bandwidth_gbps": 256,
        "memory_type": "GDDR5",
        "cuda_cores": 1920,
        "tensor_cores": 0,
        "fp32_tflops": 6.5,
        "fp16_tflops": 6.5,
        "architecture": "Pascal",
        "compute_capability": "6.1",
        "tdp_watts": 150,
        "pcie_gen": 3,
        "pcie_lanes": 16,
        "aliases": ["GTX 1070", "GTX1070", "NVIDIA GTX 1070"],
        "availability": "discontinued",
        "price_usd": 100,
    },
    {
        "name": "NVIDIA GTX 1060 6GB",
        "vendor": "nvidia",
        "vram_mb": 6144,
        "bandwidth_gbps": 192,
        "memory_type": "GDDR5",
        "cuda_cores": 1280,
        "tensor_cores": 0,
        "fp32_tflops": 4.4,
        "fp16_tflops": 4.4,
        "architecture": "Pascal",
        "compute_capability": "6.1",
        "tdp_watts": 120,
        "pcie_gen": 3,
        "pcie_lanes": 16,
        "aliases": ["GTX 1060 6GB", "GTX1060", "NVIDIA GTX 1060"],
        "availability": "discontinued",
        "price_usd": 80,
    },

    # ── NVIDIA RTX 3050 (Ampere) ──────────────────────────────────────────────

    {
        "name": "NVIDIA RTX 3060 8GB",
        "vendor": "nvidia",
        "vram_mb": 8192,
        "bandwidth_gbps": 224,
        "memory_type": "GDDR6",
        "cuda_cores": 3584,
        "tensor_cores": 112,
        "fp32_tflops": 12.7,
        "fp16_tflops": 25.4,
        "architecture": "Ampere",
        "compute_capability": "8.6",
        "tdp_watts": 170,
        "pcie_gen": 4,
        "pcie_lanes": 16,
        "aliases": ["RTX 3060 8GB", "NVIDIA RTX 3060 8GB"],
        "availability": "discontinued",
        "price_usd": 280,
    },
    {
        "name": "NVIDIA RTX 3050 8GB",
        "vendor": "nvidia",
        "vram_mb": 8192,
        "bandwidth_gbps": 224,
        "memory_type": "GDDR6",
        "cuda_cores": 2560,
        "tensor_cores": 80,
        "fp32_tflops": 9.1,
        "fp16_tflops": 18.2,
        "architecture": "Ampere",
        "compute_capability": "8.6",
        "tdp_watts": 130,
        "pcie_gen": 4,
        "pcie_lanes": 16,
        "aliases": ["RTX 3050", "RTX 3050 8GB", "NVIDIA RTX 3050"],
        "availability": "discontinued",
        "price_usd": 220,
    },

    # ── AMD RDNA4 (2025) ──────────────────────────────────────────────────────

    {
        "name": "AMD RX 9070 XT",
        "vendor": "amd",
        "vram_mb": 16384,
        "bandwidth_gbps": 768,
        "memory_type": "GDDR6",
        "cuda_cores": None,
        "tensor_cores": None,
        "fp32_tflops": 49.0,
        "fp16_tflops": 98.0,
        "architecture": "RDNA4",
        "compute_capability": None,
        "tdp_watts": 304,
        "pcie_gen": 5,
        "pcie_lanes": 16,
        "aliases": ["RX 9070 XT", "AMD RX 9070 XT", "RX9070XT"],
        "availability": "available",
        "price_usd": 599,
    },
    {
        "name": "AMD RX 9070",
        "vendor": "amd",
        "vram_mb": 16384,
        "bandwidth_gbps": 672,
        "memory_type": "GDDR6",
        "cuda_cores": None,
        "tensor_cores": None,
        "fp32_tflops": 42.2,
        "fp16_tflops": 84.4,
        "architecture": "RDNA4",
        "compute_capability": None,
        "tdp_watts": 220,
        "pcie_gen": 5,
        "pcie_lanes": 16,
        "aliases": ["RX 9070", "AMD RX 9070", "RX9070"],
        "availability": "available",
        "price_usd": 499,
    },

    # ── AMD RDNA2 additions ───────────────────────────────────────────────────

    {
        "name": "AMD RX 6600 XT",
        "vendor": "amd",
        "vram_mb": 8192,
        "bandwidth_gbps": 256,
        "memory_type": "GDDR6",
        "cuda_cores": None,
        "tensor_cores": None,
        "fp32_tflops": 21.2,
        "fp16_tflops": 21.2,
        "architecture": "RDNA2",
        "compute_capability": None,
        "tdp_watts": 160,
        "pcie_gen": 4,
        "pcie_lanes": 8,
        "aliases": ["RX 6600 XT", "AMD RX 6600 XT", "RX6600XT"],
        "availability": "discontinued",
        "price_usd": 200,
    },
    {
        "name": "AMD RX 6600",
        "vendor": "amd",
        "vram_mb": 8192,
        "bandwidth_gbps": 224,
        "memory_type": "GDDR6",
        "cuda_cores": None,
        "tensor_cores": None,
        "fp32_tflops": 17.9,
        "fp16_tflops": 17.9,
        "architecture": "RDNA2",
        "compute_capability": None,
        "tdp_watts": 132,
        "pcie_gen": 4,
        "pcie_lanes": 8,
        "aliases": ["RX 6600", "AMD RX 6600", "RX6600"],
        "availability": "discontinued",
        "price_usd": 165,
    },
    {
        "name": "AMD RX 5700 XT",
        "vendor": "amd",
        "vram_mb": 8192,
        "bandwidth_gbps": 448,
        "memory_type": "GDDR6",
        "cuda_cores": None,
        "tensor_cores": None,
        "fp32_tflops": 9.75,
        "fp16_tflops": 9.75,
        "architecture": "RDNA",
        "compute_capability": None,
        "tdp_watts": 225,
        "pcie_gen": 4,
        "pcie_lanes": 16,
        "aliases": ["RX 5700 XT", "AMD RX 5700 XT", "RX5700XT"],
        "availability": "discontinued",
        "price_usd": 150,
    },
    {
        "name": "AMD RX 5700",
        "vendor": "amd",
        "vram_mb": 8192,
        "bandwidth_gbps": 448,
        "memory_type": "GDDR6",
        "cuda_cores": None,
        "tensor_cores": None,
        "fp32_tflops": 7.95,
        "fp16_tflops": 7.95,
        "architecture": "RDNA",
        "compute_capability": None,
        "tdp_watts": 180,
        "pcie_gen": 4,
        "pcie_lanes": 16,
        "aliases": ["RX 5700", "AMD RX 5700", "RX5700"],
        "availability": "discontinued",
        "price_usd": 130,
    },

    # ── AMD Instinct (Data Center) ────────────────────────────────────────────

    {
        "name": "AMD Instinct MI300X",
        "vendor": "amd",
        "vram_mb": 196608,          # 192 GB
        "bandwidth_gbps": 5300,
        "memory_type": "HBM3",
        "cuda_cores": None,
        "tensor_cores": None,
        "fp32_tflops": 163.4,
        "fp16_tflops": 1307.4,
        "architecture": "CDNA3",
        "compute_capability": None,
        "tdp_watts": 750,
        "pcie_gen": 5,
        "pcie_lanes": 16,
        "aliases": ["MI300X", "AMD MI300X", "Instinct MI300X"],
        "availability": "available",
        "price_usd": 20000,
    },
    {
        "name": "AMD Instinct MI250X",
        "vendor": "amd",
        "vram_mb": 131072,          # 128 GB (2x64)
        "bandwidth_gbps": 3277,
        "memory_type": "HBM2e",
        "cuda_cores": None,
        "tensor_cores": None,
        "fp32_tflops": 47.9,
        "fp16_tflops": 383.0,
        "architecture": "CDNA2",
        "compute_capability": None,
        "tdp_watts": 560,
        "pcie_gen": 4,
        "pcie_lanes": 16,
        "aliases": ["MI250X", "AMD MI250X", "Instinct MI250X"],
        "availability": "available",
        "price_usd": 15000,
    },
    {
        "name": "AMD Instinct MI300A",
        "vendor": "amd",
        "vram_mb": 122880,          # 120 GB
        "bandwidth_gbps": 5300,
        "memory_type": "HBM3",
        "cuda_cores": None,
        "tensor_cores": None,
        "fp32_tflops": 122.6,
        "fp16_tflops": 980.6,
        "architecture": "CDNA3",
        "compute_capability": None,
        "tdp_watts": 550,
        "pcie_gen": 5,
        "pcie_lanes": 16,
        "aliases": ["MI300A", "AMD MI300A", "Instinct MI300A"],
        "availability": "available",
        "price_usd": 10000,
    },

    # ── Intel Arc Battlemage / Alchemist additions ────────────────────────────

    {
        "name": "Intel Arc B570",
        "vendor": "intel",
        "vram_mb": 10240,
        "bandwidth_gbps": 456,
        "memory_type": "GDDR6",
        "cuda_cores": None,
        "tensor_cores": None,
        "fp32_tflops": 19.7,
        "fp16_tflops": 39.4,
        "architecture": "Battlemage",
        "compute_capability": None,
        "tdp_watts": 150,
        "pcie_gen": 4,
        "pcie_lanes": 8,
        "aliases": ["Arc B570", "Intel Arc B570"],
        "availability": "available",
        "price_usd": 219,
    },
    {
        "name": "Intel Arc A580",
        "vendor": "intel",
        "vram_mb": 8192,
        "bandwidth_gbps": 512,
        "memory_type": "GDDR6",
        "cuda_cores": None,
        "tensor_cores": None,
        "fp32_tflops": 18.8,
        "fp16_tflops": 37.6,
        "architecture": "Alchemist",
        "compute_capability": None,
        "tdp_watts": 175,
        "pcie_gen": 4,
        "pcie_lanes": 8,
        "aliases": ["Arc A580", "Intel Arc A580"],
        "availability": "available",
        "price_usd": 179,
    },

    # ── Apple Silicon additions ───────────────────────────────────────────────

    {
        "name": "Apple M1 (16GB)",
        "vendor": "apple",
        "vram_mb": 16384,
        "bandwidth_gbps": 68.25,
        "memory_type": "LPDDR4X",
        "cuda_cores": None,
        "tensor_cores": None,
        "fp32_tflops": 2.6,
        "fp16_tflops": 5.2,
        "architecture": "M1",
        "compute_capability": None,
        "tdp_watts": 20,
        "pcie_gen": None,
        "pcie_lanes": None,
        "aliases": ["M1 16GB", "Apple M1 16GB"],
        "availability": "discontinued",
        "price_usd": 699,
    },
    {
        "name": "Apple M1 Ultra (128GB)",
        "vendor": "apple",
        "vram_mb": 131072,
        "bandwidth_gbps": 800,
        "memory_type": "LPDDR5",
        "cuda_cores": None,
        "tensor_cores": None,
        "fp32_tflops": 21.2,
        "fp16_tflops": 21.2,
        "architecture": "M1 Ultra",
        "compute_capability": None,
        "tdp_watts": 215,
        "pcie_gen": None,
        "pcie_lanes": None,
        "aliases": ["M1 Ultra 128GB", "Apple M1 Ultra 128GB"],
        "availability": "discontinued",
        "price_usd": 4999,
    },
    {
        "name": "Apple M2 (16GB)",
        "vendor": "apple",
        "vram_mb": 16384,
        "bandwidth_gbps": 100,
        "memory_type": "LPDDR5",
        "cuda_cores": None,
        "tensor_cores": None,
        "fp32_tflops": 3.6,
        "fp16_tflops": 7.2,
        "architecture": "M2",
        "compute_capability": None,
        "tdp_watts": 22,
        "pcie_gen": None,
        "pcie_lanes": None,
        "aliases": ["M2 16GB", "Apple M2 16GB"],
        "availability": "discontinued",
        "price_usd": 799,
    },
    {
        "name": "Apple M2 (24GB)",
        "vendor": "apple",
        "vram_mb": 24576,
        "bandwidth_gbps": 100,
        "memory_type": "LPDDR5",
        "cuda_cores": None,
        "tensor_cores": None,
        "fp32_tflops": 3.6,
        "fp16_tflops": 7.2,
        "architecture": "M2",
        "compute_capability": None,
        "tdp_watts": 22,
        "pcie_gen": None,
        "pcie_lanes": None,
        "aliases": ["M2 24GB", "Apple M2 24GB"],
        "availability": "discontinued",
        "price_usd": 999,
    },
    {
        "name": "Apple M2 Pro (32GB)",
        "vendor": "apple",
        "vram_mb": 32768,
        "bandwidth_gbps": 200,
        "memory_type": "LPDDR5",
        "cuda_cores": None,
        "tensor_cores": None,
        "fp32_tflops": 13.6,
        "fp16_tflops": 13.6,
        "architecture": "M2 Pro",
        "compute_capability": None,
        "tdp_watts": 30,
        "pcie_gen": None,
        "pcie_lanes": None,
        "aliases": ["M2 Pro 32GB", "Apple M2 Pro 32GB"],
        "availability": "discontinued",
        "price_usd": 1499,
    },
    {
        "name": "Apple M2 Max (64GB)",
        "vendor": "apple",
        "vram_mb": 65536,
        "bandwidth_gbps": 400,
        "memory_type": "LPDDR5",
        "cuda_cores": None,
        "tensor_cores": None,
        "fp32_tflops": 13.6,
        "fp16_tflops": 13.6,
        "architecture": "M2 Max",
        "compute_capability": None,
        "tdp_watts": 60,
        "pcie_gen": None,
        "pcie_lanes": None,
        "aliases": ["M2 Max 64GB", "Apple M2 Max 64GB"],
        "availability": "discontinued",
        "price_usd": 2299,
    },
    {
        "name": "Apple M2 Ultra (128GB)",
        "vendor": "apple",
        "vram_mb": 131072,
        "bandwidth_gbps": 800,
        "memory_type": "LPDDR5",
        "cuda_cores": None,
        "tensor_cores": None,
        "fp32_tflops": 27.2,
        "fp16_tflops": 27.2,
        "architecture": "M2 Ultra",
        "compute_capability": None,
        "tdp_watts": 215,
        "pcie_gen": None,
        "pcie_lanes": None,
        "aliases": ["M2 Ultra 128GB", "Apple M2 Ultra 128GB"],
        "availability": "discontinued",
        "price_usd": 3999,
    },
    {
        "name": "Apple M2 Ultra (192GB)",
        "vendor": "apple",
        "vram_mb": 196608,
        "bandwidth_gbps": 800,
        "memory_type": "LPDDR5",
        "cuda_cores": None,
        "tensor_cores": None,
        "fp32_tflops": 27.2,
        "fp16_tflops": 27.2,
        "architecture": "M2 Ultra",
        "compute_capability": None,
        "tdp_watts": 215,
        "pcie_gen": None,
        "pcie_lanes": None,
        "aliases": ["M2 Ultra 192GB", "Apple M2 Ultra 192GB"],
        "availability": "discontinued",
        "price_usd": 5499,
    },
    {
        "name": "Apple M3 (16GB)",
        "vendor": "apple",
        "vram_mb": 16384,
        "bandwidth_gbps": 100,
        "memory_type": "LPDDR5",
        "cuda_cores": None,
        "tensor_cores": None,
        "fp32_tflops": 3.6,
        "fp16_tflops": 7.2,
        "architecture": "M3",
        "compute_capability": None,
        "tdp_watts": 22,
        "pcie_gen": None,
        "pcie_lanes": None,
        "aliases": ["M3 16GB", "Apple M3 16GB"],
        "availability": "available",
        "price_usd": 799,
    },
    {
        "name": "Apple M3 (24GB)",
        "vendor": "apple",
        "vram_mb": 24576,
        "bandwidth_gbps": 100,
        "memory_type": "LPDDR5",
        "cuda_cores": None,
        "tensor_cores": None,
        "fp32_tflops": 3.6,
        "fp16_tflops": 7.2,
        "architecture": "M3",
        "compute_capability": None,
        "tdp_watts": 22,
        "pcie_gen": None,
        "pcie_lanes": None,
        "aliases": ["M3 24GB", "Apple M3 24GB"],
        "availability": "available",
        "price_usd": 999,
    },
    {
        "name": "Apple M3 Pro (36GB)",
        "vendor": "apple",
        "vram_mb": 36864,
        "bandwidth_gbps": 150,
        "memory_type": "LPDDR5",
        "cuda_cores": None,
        "tensor_cores": None,
        "fp32_tflops": 14.2,
        "fp16_tflops": 14.2,
        "architecture": "M3 Pro",
        "compute_capability": None,
        "tdp_watts": 30,
        "pcie_gen": None,
        "pcie_lanes": None,
        "aliases": ["M3 Pro 36GB", "Apple M3 Pro 36GB"],
        "availability": "available",
        "price_usd": 1999,
    },
    {
        "name": "Apple M3 Max (64GB)",
        "vendor": "apple",
        "vram_mb": 65536,
        "bandwidth_gbps": 300,
        "memory_type": "LPDDR5",
        "cuda_cores": None,
        "tensor_cores": None,
        "fp32_tflops": 14.2,
        "fp16_tflops": 14.2,
        "architecture": "M3 Max",
        "compute_capability": None,
        "tdp_watts": 60,
        "pcie_gen": None,
        "pcie_lanes": None,
        "aliases": ["M3 Max 64GB", "Apple M3 Max 64GB"],
        "availability": "available",
        "price_usd": 2799,
    },
    {
        "name": "Apple M3 Ultra (192GB)",
        "vendor": "apple",
        "vram_mb": 196608,
        "bandwidth_gbps": 800,
        "memory_type": "LPDDR5",
        "cuda_cores": None,
        "tensor_cores": None,
        "fp32_tflops": 28.4,
        "fp16_tflops": 28.4,
        "architecture": "M3 Ultra",
        "compute_capability": None,
        "tdp_watts": 215,
        "pcie_gen": None,
        "pcie_lanes": None,
        "aliases": ["M3 Ultra 192GB", "Apple M3 Ultra 192GB"],
        "availability": "available",
        "price_usd": 6999,
    },
    {
        "name": "Apple M4 (24GB)",
        "vendor": "apple",
        "vram_mb": 24576,
        "bandwidth_gbps": 120,
        "memory_type": "LPDDR5X",
        "cuda_cores": None,
        "tensor_cores": None,
        "fp32_tflops": 4.3,
        "fp16_tflops": 8.6,
        "architecture": "M4",
        "compute_capability": None,
        "tdp_watts": 22,
        "pcie_gen": None,
        "pcie_lanes": None,
        "aliases": ["M4 24GB", "Apple M4 24GB"],
        "availability": "available",
        "price_usd": 699,
    },
    {
        "name": "Apple M4 Pro (64GB)",
        "vendor": "apple",
        "vram_mb": 65536,
        "bandwidth_gbps": 273,
        "memory_type": "LPDDR5X",
        "cuda_cores": None,
        "tensor_cores": None,
        "fp32_tflops": 20.0,
        "fp16_tflops": 20.0,
        "architecture": "M4 Pro",
        "compute_capability": None,
        "tdp_watts": 30,
        "pcie_gen": None,
        "pcie_lanes": None,
        "aliases": ["M4 Pro 64GB", "Apple M4 Pro 64GB"],
        "availability": "available",
        "price_usd": 2599,
    },
    {
        "name": "Apple M4 Ultra (192GB)",
        "vendor": "apple",
        "vram_mb": 196608,
        "bandwidth_gbps": 1092,
        "memory_type": "LPDDR5X",
        "cuda_cores": None,
        "tensor_cores": None,
        "fp32_tflops": 40.0,
        "fp16_tflops": 40.0,
        "architecture": "M4 Ultra",
        "compute_capability": None,
        "tdp_watts": 215,
        "pcie_gen": None,
        "pcie_lanes": None,
        "aliases": ["M4 Ultra 192GB", "Apple M4 Ultra 192GB"],
        "availability": "available",
        "price_usd": 7499,
    },
    {
        "name": "Apple M4 Ultra (384GB)",
        "vendor": "apple",
        "vram_mb": 393216,
        "bandwidth_gbps": 1092,
        "memory_type": "LPDDR5X",
        "cuda_cores": None,
        "tensor_cores": None,
        "fp32_tflops": 40.0,
        "fp16_tflops": 40.0,
        "architecture": "M4 Ultra",
        "compute_capability": None,
        "tdp_watts": 215,
        "pcie_gen": None,
        "pcie_lanes": None,
        "aliases": ["M4 Ultra 384GB", "Apple M4 Ultra 384GB"],
        "availability": "available",
        "price_usd": 9999,
    },
]

# ── Merge ──────────────────────────────────────────────────────────────────────

with open("public/data/gpus.json") as f:
    existing = json.load(f)

existing_names = {g["name"] for g in existing}
added = 0
for g in NEW_GPUS:
    if g["name"] not in existing_names:
        existing.append(g)
        added += 1
    else:
        print(f"  SKIP: {g['name']}")

with open("public/data/gpus.json", "w") as f:
    json.dump(existing, f, indent=2)

print(f"\nAdded {added} GPUs. Total: {len(existing)}")
vendors = {}
for g in existing:
    v = g["vendor"]
    vendors[v] = vendors.get(v, 0) + 1
for v, c in sorted(vendors.items(), key=lambda x: -x[1]):
    print(f"  {v}: {c}")
