#!/usr/bin/env python3
"""
Expand public/data/cpus.json with comprehensive CPU data.
Adds AMD Zen 5 / 3D V-Cache, Intel Arrow Lake, EPYC, Threadripper PRO, Apple Ultra.
"""
import json

NEW_CPUS = [

    # ── AMD Ryzen 9000 series (Zen 5, 2024) ────────────────────────────────────

    {
        "name": "AMD Ryzen 9 9950X",
        "vendor": "amd",
        "cores": 16,
        "threads": 32,
        "base_clock_ghz": 4.3,
        "boost_clock_ghz": 5.7,
        "l3_cache_mb": 64,
        "avx": True, "avx2": True, "avx512": True,
        "max_ram_gb": 256,
        "ram_channels": 2,
        "max_ram_speed_mhz": 5600,
        "tdp_watts": 170,
    },
    {
        "name": "AMD Ryzen 9 9900X",
        "vendor": "amd",
        "cores": 12,
        "threads": 24,
        "base_clock_ghz": 4.4,
        "boost_clock_ghz": 5.6,
        "l3_cache_mb": 64,
        "avx": True, "avx2": True, "avx512": True,
        "max_ram_gb": 256,
        "ram_channels": 2,
        "max_ram_speed_mhz": 5600,
        "tdp_watts": 120,
    },
    {
        "name": "AMD Ryzen 7 9700X",
        "vendor": "amd",
        "cores": 8,
        "threads": 16,
        "base_clock_ghz": 3.8,
        "boost_clock_ghz": 5.5,
        "l3_cache_mb": 32,
        "avx": True, "avx2": True, "avx512": True,
        "max_ram_gb": 256,
        "ram_channels": 2,
        "max_ram_speed_mhz": 5600,
        "tdp_watts": 65,
    },
    {
        "name": "AMD Ryzen 5 9600X",
        "vendor": "amd",
        "cores": 6,
        "threads": 12,
        "base_clock_ghz": 3.9,
        "boost_clock_ghz": 5.4,
        "l3_cache_mb": 32,
        "avx": True, "avx2": True, "avx512": True,
        "max_ram_gb": 256,
        "ram_channels": 2,
        "max_ram_speed_mhz": 5600,
        "tdp_watts": 65,
    },

    # ── AMD 3D V-Cache ──────────────────────────────────────────────────────────

    {
        "name": "AMD Ryzen 9 7950X3D",
        "vendor": "amd",
        "cores": 16,
        "threads": 32,
        "base_clock_ghz": 4.2,
        "boost_clock_ghz": 5.7,
        "l3_cache_mb": 128,
        "avx": True, "avx2": True, "avx512": True,
        "max_ram_gb": 128,
        "ram_channels": 2,
        "max_ram_speed_mhz": 5200,
        "tdp_watts": 120,
    },
    {
        "name": "AMD Ryzen 7 5800X3D",
        "vendor": "amd",
        "cores": 8,
        "threads": 16,
        "base_clock_ghz": 3.4,
        "boost_clock_ghz": 4.5,
        "l3_cache_mb": 96,
        "avx": True, "avx2": True, "avx512": False,
        "max_ram_gb": 128,
        "ram_channels": 2,
        "max_ram_speed_mhz": 3200,
        "tdp_watts": 105,
    },

    # ── AMD Ryzen 5000 additions ────────────────────────────────────────────────

    {
        "name": "AMD Ryzen 5 5600X",
        "vendor": "amd",
        "cores": 6,
        "threads": 12,
        "base_clock_ghz": 3.7,
        "boost_clock_ghz": 4.6,
        "l3_cache_mb": 32,
        "avx": True, "avx2": True, "avx512": False,
        "max_ram_gb": 128,
        "ram_channels": 2,
        "max_ram_speed_mhz": 3200,
        "tdp_watts": 65,
    },
    {
        "name": "AMD Ryzen 5 5600",
        "vendor": "amd",
        "cores": 6,
        "threads": 12,
        "base_clock_ghz": 3.5,
        "boost_clock_ghz": 4.4,
        "l3_cache_mb": 32,
        "avx": True, "avx2": True, "avx512": False,
        "max_ram_gb": 128,
        "ram_channels": 2,
        "max_ram_speed_mhz": 3200,
        "tdp_watts": 65,
    },
    {
        "name": "AMD Ryzen 7 5700X",
        "vendor": "amd",
        "cores": 8,
        "threads": 16,
        "base_clock_ghz": 3.4,
        "boost_clock_ghz": 4.6,
        "l3_cache_mb": 32,
        "avx": True, "avx2": True, "avx512": False,
        "max_ram_gb": 128,
        "ram_channels": 2,
        "max_ram_speed_mhz": 3200,
        "tdp_watts": 65,
    },

    # ── AMD Ryzen 7000 additions ────────────────────────────────────────────────

    {
        "name": "AMD Ryzen 9 7900",
        "vendor": "amd",
        "cores": 12,
        "threads": 24,
        "base_clock_ghz": 3.7,
        "boost_clock_ghz": 5.4,
        "l3_cache_mb": 64,
        "avx": True, "avx2": True, "avx512": True,
        "max_ram_gb": 128,
        "ram_channels": 2,
        "max_ram_speed_mhz": 5200,
        "tdp_watts": 65,
    },
    {
        "name": "AMD Ryzen 7 7700",
        "vendor": "amd",
        "cores": 8,
        "threads": 16,
        "base_clock_ghz": 3.8,
        "boost_clock_ghz": 5.3,
        "l3_cache_mb": 32,
        "avx": True, "avx2": True, "avx512": True,
        "max_ram_gb": 128,
        "ram_channels": 2,
        "max_ram_speed_mhz": 5200,
        "tdp_watts": 65,
    },
    {
        "name": "AMD Ryzen 5 7600",
        "vendor": "amd",
        "cores": 6,
        "threads": 12,
        "base_clock_ghz": 3.8,
        "boost_clock_ghz": 5.1,
        "l3_cache_mb": 32,
        "avx": True, "avx2": True, "avx512": True,
        "max_ram_gb": 128,
        "ram_channels": 2,
        "max_ram_speed_mhz": 5200,
        "tdp_watts": 65,
    },

    # ── AMD Threadripper 7000 additional ─────────────────────────────────────────

    {
        "name": "AMD Threadripper 7960X",
        "vendor": "amd",
        "cores": 24,
        "threads": 48,
        "base_clock_ghz": 4.2,
        "boost_clock_ghz": 5.3,
        "l3_cache_mb": 128,
        "avx": True, "avx2": True, "avx512": True,
        "max_ram_gb": 2048,
        "ram_channels": 8,
        "max_ram_speed_mhz": 5200,
        "tdp_watts": 350,
    },

    # ── AMD Threadripper PRO 5000 (Zen 3) ────────────────────────────────────────

    {
        "name": "AMD Threadripper PRO 5995WX",
        "vendor": "amd",
        "cores": 64,
        "threads": 128,
        "base_clock_ghz": 2.7,
        "boost_clock_ghz": 4.5,
        "l3_cache_mb": 256,
        "avx": True, "avx2": True, "avx512": False,
        "max_ram_gb": 2048,
        "ram_channels": 8,
        "max_ram_speed_mhz": 4000,
        "tdp_watts": 280,
    },
    {
        "name": "AMD Threadripper PRO 5975WX",
        "vendor": "amd",
        "cores": 32,
        "threads": 64,
        "base_clock_ghz": 3.6,
        "boost_clock_ghz": 4.5,
        "l3_cache_mb": 128,
        "avx": True, "avx2": True, "avx512": False,
        "max_ram_gb": 2048,
        "ram_channels": 8,
        "max_ram_speed_mhz": 4000,
        "tdp_watts": 280,
    },

    # ── AMD EPYC (Server) ─────────────────────────────────────────────────────────

    {
        "name": "AMD EPYC 9754",
        "vendor": "amd",
        "cores": 128,
        "threads": 256,
        "base_clock_ghz": 2.25,
        "boost_clock_ghz": 3.1,
        "l3_cache_mb": 256,
        "avx": True, "avx2": True, "avx512": True,
        "max_ram_gb": 6144,
        "ram_channels": 12,
        "max_ram_speed_mhz": 4800,
        "tdp_watts": 360,
    },
    {
        "name": "AMD EPYC 9654",
        "vendor": "amd",
        "cores": 96,
        "threads": 192,
        "base_clock_ghz": 2.4,
        "boost_clock_ghz": 3.7,
        "l3_cache_mb": 384,
        "avx": True, "avx2": True, "avx512": True,
        "max_ram_gb": 6144,
        "ram_channels": 12,
        "max_ram_speed_mhz": 4800,
        "tdp_watts": 360,
    },
    {
        "name": "AMD EPYC 9554",
        "vendor": "amd",
        "cores": 64,
        "threads": 128,
        "base_clock_ghz": 3.1,
        "boost_clock_ghz": 3.75,
        "l3_cache_mb": 256,
        "avx": True, "avx2": True, "avx512": True,
        "max_ram_gb": 6144,
        "ram_channels": 12,
        "max_ram_speed_mhz": 4800,
        "tdp_watts": 360,
    },
    {
        "name": "AMD EPYC 7763",
        "vendor": "amd",
        "cores": 64,
        "threads": 128,
        "base_clock_ghz": 2.45,
        "boost_clock_ghz": 3.5,
        "l3_cache_mb": 256,
        "avx": True, "avx2": True, "avx512": False,
        "max_ram_gb": 4096,
        "ram_channels": 8,
        "max_ram_speed_mhz": 3200,
        "tdp_watts": 280,
    },

    # ── Intel Arrow Lake (Core Ultra 200, 2024) ─────────────────────────────────

    {
        "name": "Intel Core Ultra 9 285K",
        "vendor": "intel",
        "cores": 24,
        "threads": 24,
        "p_cores": 8,
        "e_cores": 16,
        "base_clock_ghz": 3.7,
        "boost_clock_ghz": 5.7,
        "l3_cache_mb": 36,
        "avx": True, "avx2": True, "avx512": False,
        "max_ram_gb": 192,
        "ram_channels": 2,
        "max_ram_speed_mhz": 6400,
        "tdp_watts": 125,
    },
    {
        "name": "Intel Core Ultra 7 265K",
        "vendor": "intel",
        "cores": 20,
        "threads": 20,
        "p_cores": 8,
        "e_cores": 12,
        "base_clock_ghz": 3.9,
        "boost_clock_ghz": 5.5,
        "l3_cache_mb": 30,
        "avx": True, "avx2": True, "avx512": False,
        "max_ram_gb": 192,
        "ram_channels": 2,
        "max_ram_speed_mhz": 6400,
        "tdp_watts": 125,
    },
    {
        "name": "Intel Core Ultra 5 245K",
        "vendor": "intel",
        "cores": 14,
        "threads": 14,
        "p_cores": 6,
        "e_cores": 8,
        "base_clock_ghz": 4.2,
        "boost_clock_ghz": 5.2,
        "l3_cache_mb": 24,
        "avx": True, "avx2": True, "avx512": False,
        "max_ram_gb": 192,
        "ram_channels": 2,
        "max_ram_speed_mhz": 6400,
        "tdp_watts": 125,
    },

    # ── Intel Alder Lake (12th gen) additions ────────────────────────────────────

    {
        "name": "Intel Core i7-12700K",
        "vendor": "intel",
        "cores": 12,
        "threads": 20,
        "p_cores": 8,
        "e_cores": 4,
        "base_clock_ghz": 3.6,
        "boost_clock_ghz": 5.0,
        "l3_cache_mb": 25,
        "avx": True, "avx2": True, "avx512": False,
        "max_ram_gb": 128,
        "ram_channels": 2,
        "max_ram_speed_mhz": 4800,
        "tdp_watts": 125,
    },
    {
        "name": "Intel Core i5-12600K",
        "vendor": "intel",
        "cores": 10,
        "threads": 16,
        "p_cores": 6,
        "e_cores": 4,
        "base_clock_ghz": 3.7,
        "boost_clock_ghz": 4.9,
        "l3_cache_mb": 20,
        "avx": True, "avx2": True, "avx512": False,
        "max_ram_gb": 128,
        "ram_channels": 2,
        "max_ram_speed_mhz": 4800,
        "tdp_watts": 125,
    },

    # ── Intel Xeon Scalable (server) ──────────────────────────────────────────────

    {
        "name": "Intel Xeon Platinum 8480+",
        "vendor": "intel",
        "cores": 60,
        "threads": 120,
        "base_clock_ghz": 2.0,
        "boost_clock_ghz": 3.8,
        "l3_cache_mb": 105,
        "avx": True, "avx2": True, "avx512": True,
        "amx": True,
        "max_ram_gb": 4096,
        "ram_channels": 8,
        "max_ram_speed_mhz": 4800,
        "tdp_watts": 350,
    },
    {
        "name": "Intel Xeon Gold 6338",
        "vendor": "intel",
        "cores": 32,
        "threads": 64,
        "base_clock_ghz": 2.0,
        "boost_clock_ghz": 3.2,
        "l3_cache_mb": 48,
        "avx": True, "avx2": True, "avx512": True,
        "max_ram_gb": 6144,
        "ram_channels": 8,
        "max_ram_speed_mhz": 3200,
        "tdp_watts": 205,
    },

    # ── Apple Silicon Ultra ────────────────────────────────────────────────────────

    {
        "name": "Apple M1 Ultra",
        "vendor": "apple",
        "cores": 20,
        "threads": 20,
        "p_cores": 16,
        "e_cores": 4,
        "base_clock_ghz": 3.2,
        "l3_cache_mb": 192,
        "avx": False, "avx2": False, "avx512": False,
        "max_ram_gb": 128,
        "ram_channels": 1,
        "max_ram_speed_mhz": 6400,
        "tdp_watts": 215,
    },
    {
        "name": "Apple M2 Ultra",
        "vendor": "apple",
        "cores": 24,
        "threads": 24,
        "p_cores": 16,
        "e_cores": 8,
        "base_clock_ghz": 3.49,
        "l3_cache_mb": 192,
        "avx": False, "avx2": False, "avx512": False,
        "max_ram_gb": 192,
        "ram_channels": 1,
        "max_ram_speed_mhz": 8533,
        "tdp_watts": 215,
    },
    {
        "name": "Apple M3 Ultra",
        "vendor": "apple",
        "cores": 32,
        "threads": 32,
        "p_cores": 24,
        "e_cores": 8,
        "base_clock_ghz": 4.05,
        "l3_cache_mb": 256,
        "avx": False, "avx2": False, "avx512": False,
        "max_ram_gb": 192,
        "ram_channels": 1,
        "max_ram_speed_mhz": 8533,
        "tdp_watts": 215,
    },
    {
        "name": "Apple M4 Ultra",
        "vendor": "apple",
        "cores": 32,
        "threads": 32,
        "p_cores": 24,
        "e_cores": 8,
        "base_clock_ghz": 4.4,
        "l3_cache_mb": 256,
        "avx": False, "avx2": False, "avx512": False,
        "max_ram_gb": 384,
        "ram_channels": 1,
        "max_ram_speed_mhz": 9600,
        "tdp_watts": 215,
    },

    # ── Budget / mainstream (older still widely used) ──────────────────────────────

    {
        "name": "Intel Core i9-10900K",
        "vendor": "intel",
        "cores": 10,
        "threads": 20,
        "base_clock_ghz": 3.7,
        "boost_clock_ghz": 5.3,
        "l3_cache_mb": 20,
        "avx": True, "avx2": True, "avx512": False,
        "max_ram_gb": 128,
        "ram_channels": 2,
        "max_ram_speed_mhz": 2933,
        "tdp_watts": 125,
    },
    {
        "name": "Intel Core i7-11700K",
        "vendor": "intel",
        "cores": 8,
        "threads": 16,
        "base_clock_ghz": 3.6,
        "boost_clock_ghz": 5.0,
        "l3_cache_mb": 16,
        "avx": True, "avx2": True, "avx512": True,
        "max_ram_gb": 128,
        "ram_channels": 2,
        "max_ram_speed_mhz": 3200,
        "tdp_watts": 125,
    },
    {
        "name": "AMD Ryzen 9 3900X",
        "vendor": "amd",
        "cores": 12,
        "threads": 24,
        "base_clock_ghz": 3.8,
        "boost_clock_ghz": 4.6,
        "l3_cache_mb": 64,
        "avx": True, "avx2": True, "avx512": False,
        "max_ram_gb": 128,
        "ram_channels": 2,
        "max_ram_speed_mhz": 3200,
        "tdp_watts": 105,
    },
    {
        "name": "AMD Ryzen 7 3700X",
        "vendor": "amd",
        "cores": 8,
        "threads": 16,
        "base_clock_ghz": 3.6,
        "boost_clock_ghz": 4.4,
        "l3_cache_mb": 32,
        "avx": True, "avx2": True, "avx512": False,
        "max_ram_gb": 128,
        "ram_channels": 2,
        "max_ram_speed_mhz": 3200,
        "tdp_watts": 65,
    },
]

# ── Merge ──────────────────────────────────────────────────────────────────────

with open("public/data/cpus.json") as f:
    existing = json.load(f)

existing_names = {c["name"] for c in existing}
added = 0
for c in NEW_CPUS:
    if c["name"] not in existing_names:
        existing.append(c)
        added += 1
    else:
        print(f"  SKIP: {c['name']}")

with open("public/data/cpus.json", "w") as f:
    json.dump(existing, f, indent=2)

print(f"\nAdded {added} CPUs. Total: {len(existing)}")
vendors = {}
for c in existing:
    v = c["vendor"]
    vendors[v] = vendors.get(v, 0) + 1
for v, cnt in sorted(vendors.items(), key=lambda x: -x[1]):
    print(f"  {v}: {cnt}")
